### ISSUE TITLE
Computercraft has unchanged recipes

### ISSUE THREAD

**Issue by rowanthemodder** [simibubi/Above-and-Beyond#10]
See title, this is an issue since you can google programs for most automation tasks done with create and then some.
It's even further an issue since they're extremely cheap, some stone, a redstone dust, a glass pane, a chest, and a diamond tool for a turtle which does a specific task.
Mining turtles in particular are ridiculously powerful as all you need to make a quarry is said materials and lots of furnace fuel.

**Comment by simibubi** [comment]
Thanks for the report.
I don't see it as a huge problem to the packs integrity, but in v1.1 turtles involve a slight bit of extra effort to get.
