### ISSUE TITLE
Game crashes when placing an orbital laser drill

### ISSUE THREAD

**Issue by ayedabb** [simibubi/Above-and-Beyond#100]
I placed an orbital laser drill on the ground after getting it as loot from a pot, after doing so I lost my world completely and have been unable to recover it

Crash Report
![image](https://user-images.githubusercontent.com/55286176/141213925-1e0d992b-7728-40e9-a06f-4e9116261665.png)

Full Crash Log
[crash-2021-11-10_19.11.11-client.txt](https://github.com/simibubi/Above-and-Beyond/files/7516721/crash-2021-11-10_19.11.11-client.txt)

**Comment by fkyah3** [comment]
have a way to fix it ，se map editor delete that ting

**Comment by UnderscoreKilburn** [comment]
A lot of problematic items were blacklisted from Randomium ore and treasure pots so this should no longer be an issue, closing.
