### ISSUE TITLE
Destabilized Redstone recipe from Sky Solution and Charged Certus Quartz is not working with a mixer

### ISSUE THREAD

**Issue by orangedude27** [simibubi/Above-and-Beyond#102]
There is over 250 mb worth of Sky solution in the basin and we are adding the certus quartz. 

Any help would be cool!

**Comment by Geartwo** [comment]
It don't work when the basin creates a output. Use a brass funnel as output then it will work.

**Comment by MirceaZisu** [comment]
You should try outputting both the item and fluid from the same side. Liquid goes in item drain, item rolls over and ends up on a belt.

**Comment by orangedude27** [comment]
@Geartwo 
That fixed it. Thanks!
