### ISSUE TITLE
Enchanted Saw is Turned to Breakable in Crafting Table

### ISSUE THREAD

**Issue by Phoupraw** [simibubi/Above-and-Beyond#103]
Version: 1.1
Enchanted Saw is an unbreakable diamond saw as a prise of a FTB quest. When it is used to craft kinetic mechanism in crafting table, it becomes a normal diamond saw which is no longer unbreakble.
![avatar](https://i.loli.net/2021/11/11/RYPQdJmStlNGHrv.png)![avatar](https://i.loli.net/2021/11/11/9OciEekfIRDBTxV.png)
Is this by design?

**Comment by GoliathX211** [comment]
I was not aware you could even craft the mechanisms in the crafting grid.

**Comment by Phoupraw** [comment]
> I was not aware you could even craft the mechanisms in the crafting grid.

Because in version 1.1, crafting it in crafting grid is cheaper than Sequenced Assembly.

**Comment by AugustDay** [comment]
+1, happened to me too. 
If only the FTB quest was repeatable, lol.  

If you got hit with this bug and need a way to get your unbreakable saw back, I figured out a workaround using commands. The item **forbidden_arcanus:eternal_stella** can give the Indestructible enchant to tools, so just /give yourself 1 and use it on the diamond saw (Smithing Table):
`/give PLAYERNAME forbidden_arcanus:eternal_stella`

**Comment by Phoupraw** [comment]
> +1, happened to me too. If only the FTB quest was repeatable, lol.
> 
> If you got hit with this bug and need a way to get your unbreakable saw back, I figured out a workaround using commands. The item **forbidden_arcanus:eternal_stella** can give the Indestructible enchant to tools, so just /give yourself 1 and use it on the diamond saw (Smithing Table): `/give PLAYERNAME forbidden_arcanus:eternal_stella`

Oh, yes. There is another manner besides: Run command `/ftbquests editing_mode`, and you can reset the quest and attain it again.
