### ISSUE TITLE
I cant start the game

### ISSUE THREAD

**Issue by TanjiroSkies** [simibubi/Above-and-Beyond#107]
i have just installed the modpack and for some reason i continue to get this error 
![image](https://user-images.githubusercontent.com/94139744/141358179-55d52fb9-917e-48e5-a613-bc490335e1d0.png)
i have not touched the mod folder 
crash log below
[latest.log](https://github.com/simibubi/Above-and-Beyond/files/7522870/latest.log)

**Comment by Geartwo** [comment]
Wrong Java Version you need 1.8 or at highest 11.
