### ISSUE TITLE
Randomium ore can give disabled items

### ISSUE THREAD

**Issue by rowanthemodder** [simibubi/Above-and-Beyond#11]
See title, all it would take to fix is adding disabled items to the tag #randomium:blacklist.

**Comment by simibubi** [comment]
Thanks for the issue-
best I can do is gradually deny-list item ids as they are being reported. Feel free to compile a list of items you consider problematic. 
Otherwise there is always a bit of fun in the prospect of finding something not necessarily intended to get hold of 😉
