### ISSUE TITLE
Not possible to make occultism crusher on servers

### ISSUE THREAD

**Issue by LuciferFX** [simibubi/Above-and-Beyond#114]
It is not possible to make a crusher spirit from occultism in a server/multiplayer preventing people from getting endstone dust and progressing in occultism. May be disabled in config.

**Comment by GoliathX211** [comment]
I play on the same server as Lucifer and the server host confirmed it is not a config option yesterday I believe.

**Comment by ElKameleon** [comment]
If you are reading the book for occultism, it's not right. Check JEI for the ritual, zinc is swapped in for silver. We had the same issue on my server.

**Comment by cking** [comment]
![image](https://user-images.githubusercontent.com/196108/143495721-542b1b58-d1f5-484b-a1a1-f5d7796be32b.png)
im on a server, this is what the bowls hold with the chat message.

you cant even get silver in this pack can you?
