### ISSUE TITLE
All of the shipments cost 10 silver [Ver 1.1]

### ISSUE THREAD

**Issue by zappermax** [simibubi/Above-and-Beyond#116]
Every single shipment I've noticed has a description that seems to label the intentional price but the 'Task' indicates that the real price is 10 silver. Did I mess up the installation? If not then this needs to be fixed.

Here's a few examples of what I'm talking about:
![image](https://user-images.githubusercontent.com/29196045/141615493-43d77f6c-bf65-4110-b7d7-af07170189f9.png)

![image](https://user-images.githubusercontent.com/29196045/141615504-f241e0fd-6cf3-4e19-b491-437e09807257.png)

![image](https://user-images.githubusercontent.com/29196045/141615510-ac0b6aef-c2b4-4c03-9e94-73d4c0d8dc3e.png)

![image](https://user-images.githubusercontent.com/29196045/141615514-aecc7298-d0c2-4522-a1b8-e176a0a984f9.png)

**Comment by PieOrPi** [comment]
You're paying 10 silver for the import card itself, the price it specifies is how much you need to pay in the trade station for the item.

**Comment by zappermax** [comment]
Ooh that’s how they work. My bad
