### ISSUE TITLE
Multiple bugs involving crafting fairy lights together

### ISSUE THREAD

**Issue by PieOrPi** [simibubi/Above-and-Beyond#117]
When crafting together two stacks of any size stack of lights from fairy lights it will crash the game when shift-clicking to result (it causes it to stop responding but I'm too impatient to wait it out so a crash in my book) if you're using a regular crafting interface or inventory crafting (I haven't tested other crafting interfaces as I don't want to crash and reopen the game over and over to test). But in the Occultism storage crafting interface shift-clicking the result will end up duplicating the lights and give you "Dyed" versions of the light. It also allows you to create stacks of an infinite amount due to how it duplicates them. Crafting a fairy light with another usually seems to just redye the light to the other's color while only consuming the one redye.

**Comment by UnderscoreKilburn** [comment]
Yup, can confirm this. Considering the mod hasn't been updated in a long time and this is a relatively minor feature, I'd say we can disable that one for now.
