### ISSUE TITLE
(optifine) Antialiasing and anisotropic filtering doesnt load some textures correctly

### ISSUE THREAD

**Issue by Wrenn96** [simibubi/Above-and-Beyond#119]
I know that Optifine wasn't really meant to be in this mod pack and it shouldn't matter to the pack creators about other mod compatibility but I was hoping that this could get fixed. Basically, whenever either of these two settings have a value >0 some textures turn into basic colors. I have only seen this on the wooden glass and basically all of the CBMicroblock glass, but that's just because I cant try every block in the pack. Again, I know that it isn't really the creator's problem but others may have this problem especially since many people use Optifine for either performance or shaders. Below are a hollow glass cover, black stained glass slab, spruce window, warped window, and crimson window in order.
![2021-11-13_11 39 55](https://user-images.githubusercontent.com/78426085/141651901-6dd0c39d-4b50-49d2-b520-29d650a8609a.png)
.

**Comment by legitswitch** [comment]
This is an optifine issue and happens on other modpacks too. Optifine anisotropic filtering and CBMicroblocks have the same issue on FTB OceanBlock for example.
