### ISSUE TITLE
Andesite generator on server generates ores

### ISSUE THREAD

**Issue by zadxdaz** [simibubi/Above-and-Beyond#12]
I opened a server with mi friends and when i made the andesite generator it started to create vanilla ores. changed the config for the mod for the config on my singleplayer profile and now it works as intended.

im sorry if my english is difficult to understand, it isnt my mother lenguaje.

**Comment by simibubi** [comment]
This happens when the config file `cobblegenrandomizer-common.toml` is not present or invalid.
Make sure the config provided by the pack is on the server and didn't get modified in the upload
