### ISSUE TITLE
Extended caves config doesn't effect world generation

### ISSUE THREAD

**Issue by Improv** [simibubi/Above-and-Beyond#13]
Don't know if this is intentional or not but trying to disable broken stone in the extended caves config doesn't get rid of it in newly created worlds.

**Comment by simibubi** [comment]
Yup, sorry. Not much I can do about this: https://github.com/polyvalord/extcaves/issues/40

**Comment by eilamg** [comment]
Given there's been no reply to the linked issue, would you consider removing Extended Caves from the modpack? It adds a bunch of nice things, but broken stone is an incredible nuisance, and being unable to reliable disable it is an issue.

Alternatively, how deeply integrated is the mod in the pack? Would manually removing it cause any significant problems?
