### ISSUE TITLE
Deployers can't place blocks if the chunk is claimed

### ISSUE THREAD

**Issue by Retr0-Wolf** [simibubi/Above-and-Beyond#131]
I was trying to make a tree farm and noticed the deployers were not placing the saplings, after a lot of frustration I realised that when I unclaimed the chunk I was building in the deployer was working again, pls fix so I can still have the area claimed.

**Comment by afolk2** [comment]
This is probably from ftb chunk permissions, can you try to set your permission to public and see if they work?

**Comment by Retr0-Wolf** [comment]
Oh okay thank you I haven't tried that

**Comment by Retr0-Wolf** [comment]
Ok ye that fixes it thank you so much I should probably close this issue now
