### ISSUE TITLE
Error to loading 2 mods

### ISSUE THREAD

**Issue by GraphBoberIV** [simibubi/Above-and-Beyond#135]
I used MultiMC, I didn't change anything.
![image](https://user-images.githubusercontent.com/94355805/141751430-ba6983e0-bc2c-40cf-82ae-443ab68d5653.png)

**Comment by WexCore** [comment]
This modpack requires Java 8

**Comment by HeWhoThreadsLightly** [comment]
Duplicate issues
https://github.com/simibubi/Above-and-Beyond/issues/135
https://github.com/simibubi/Above-and-Beyond/issues/169
https://github.com/simibubi/Above-and-Beyond/issues/172
https://github.com/simibubi/Above-and-Beyond/issues/331
