### ISSUE TITLE
Oak Leaves Unbreakable.

### ISSUE THREAD

**Issue by BoarQueen** [simibubi/Above-and-Beyond#138]
Upon breaking oak leaves, they will "break", becoming invisible, but still unable to be moved through. Sometimes they will reappear repeatedly and have to be broken repeatedly to get to the wood behind them. They decay without wood as normal, and other leaves do not have this issue.

**Comment by BoarQueen** [comment]
I've discovered it's other leaves as well? But not all of them? I'm unsure of why they do it most of the time but not sometimes. It seems only when they're connected to a tree, maybe?

**Comment by MirceaZisu** [comment]
That's a discrepancy between server and client. They're not unbreakable, but they become ghost blocks. https://bugs.mojang.com/browse/MC-156852

**Comment by VallenFrostweaver** [comment]
I've been experiencing this as well but it isn't involving high tier harvesting tools. It's just breaking the leaves 0 even by hand does this. We can only reproduce this in our LAN world though as it seems fine on single player.
