### ISSUE TITLE
Optifine incompatible (?) with Above and Beyeond

### ISSUE THREAD

**Issue by oskargarlinski** [simibubi/Above-and-Beyond#139]
Hi, I just tried adding optifine to the modpack which in theory should've worked as stated on the project page but everytime I try to launch the game, it just doesn't launch and crashes on startup. 

I tried the G8, G7 and G6 versions for 1.16.5 and they all produce the same results. To make sure that it wasn't a fluke, I also removed optifine altogether after trying to install it and the game launched fine afterwards.

Here's the crashlog:
[crash-2021-11-15_20.15.04-client.txt](https://github.com/simibubi/Above-and-Beyond/files/7541423/crash-2021-11-15_20.15.04-client.txt)

**Comment by WexCore** [comment]
Are you sure you are using Optifine 1.16.5? In the crashlog it says `OptiFine_1.16.4_HD_U_G7.jar`

**Comment by oskargarlinski** [comment]
> Are you sure you are using Optifine 1.16.5? In the crashlog it says `OptiFine_1.16.4_HD_U_G7.jar`

Yup sorry I was also experimenting with other versions to see if that would've changed anything, here's the reports including the other versions of OptiFine.

[crash-2021-11-15_20.05.45-client.txt](https://github.com/simibubi/Above-and-Beyond/files/7541934/crash-2021-11-15_20.05.45-client.txt)
[crash-2021-11-15_20.11.04-client.txt](https://github.com/simibubi/Above-and-Beyond/files/7541935/crash-2021-11-15_20.11.04-client.txt)
[crash-2021-11-15_20.12.58-client.txt](https://github.com/simibubi/Above-and-Beyond/files/7541936/crash-2021-11-15_20.12.58-client.txt)

**Comment by GE0NE** [comment]
Optifine works wonderfully with this pack for me. Try leaving it alone when it's starting up. If it freezes or hangs on the loading screen then just let it do its thing, it can sometimes take 15 mins to start. I found if I tab out while it's loading the menu or if I get impatient, then it will crash. 

Additionally, ensure the modpack is being given enough RAM, I suggest at least 5gb.

**Comment by SirChamomile** [comment]
Yeah running this with Optifine PTGI shaders I have to allocate 7-8 GB. Even then, some of the create textures don't render correctly due to texture layering I believe.
