### ISSUE TITLE
Ghast and creeper sound

### ISSUE THREAD

**Issue by EkutoruSama** [simibubi/Above-and-Beyond#14]
I walk in the overworld, when sometimes I hear a creeper or a ghast for no reason.

Biome : Lavender

Optifine : Yes

**Comment by ferekan** [comment]
This is a known feature of forbidden & arcanus.

**Comment by ferekan** [comment]
To clarify, this is the sanity feature of forbidden & arcanus.

**Comment by EkutoruSama** [comment]
Alright, I was scared of my game, sorry and thank you <3

**Comment by simibubi** [comment]
I'm sorry, I don't quite follow. 
Is the issue resolved or does the modpack have a malfunction?

**Comment by EkutoruSama** [comment]
I don't know how this is possible, but this problem is no longer present. If he comes back I will contact you directly

I supposed the isses was resolved

**Comment by rwilliaise** [comment]
I think this is due to corruption from Forbidden and Arcanus. If you kill enough passive animals, it will grant you some debilitating effects.
