### ISSUE TITLE
Modpack just stopped working for no reason

### ISSUE THREAD

**Issue by Razgriz-3** [simibubi/Above-and-Beyond#140]
The only mods I've added are Performant and Optifine which ran fine for days and now it just won't start, with or without them.
Here's the logs
[New Paste 1.txt](https://github.com/simibubi/Above-and-Beyond/files/7542036/New.Paste.1.txt)
It's also worth noting that literally earlier today the game launched and I got to the main menu. I couldn't load a world however, as my power went out right after. Maybe that broke something?

**Comment by Drakoflame** [comment]
Try removing Performant and see if it works. If the issue persists try re-downloading the pack and transfering your save over
