### ISSUE TITLE
Mechanical Crafter on belt via Schematic Cannon causing crash

### ISSUE THREAD

**Issue by Edd-William** [simibubi/Above-and-Beyond#141]
I was building a design in a single-player creative world, and had brought it to a single-player survival world to use a schematic cannon to build it. After finishing up the factory and powering everything, I was very quickly thrown off by a crash to the desktop. 

I read through the crash log quickly to find that there was a ticking block entity error. I changed `removeErroringTileEntities` to `true` in `forge-server.toml` config so I could enter the world and see if I could remove the broken block. Replacing the mechanical crafter by hand had seemed to fix the bug in the end. 

I did some other experimentation by changing the length of the belt leading to the crafter, but no matter what, if a mechanical crafter was placed on a belt by a schematic cannon, and fed by an andesite funnel; it would cause a crash.

I will attach a picture of the design I used to test the bug out, as well as the relevant crash log
![image](https://user-images.githubusercontent.com/92821096/141944249-6363a8ea-cfe6-42d2-b4b0-3926657e28fb.png)
[crash-2021-11-16_02.43.33-server.txt](https://github.com/simibubi/Above-and-Beyond/files/7544348/crash-2021-11-16_02.43.33-server.txt)

**Comment by ejgibs** [comment]
I just discovered a similar bug with the mechanical crafter placed by a Schematicannon.

**Comment by UnderscoreKilburn** [comment]
This was fixed in Create 0.3.2g, closing.
