### ISSUE TITLE
FTB Chunks makes server instantly crash

### ISSUE THREAD

**Issue by V0ru5** [simibubi/Above-and-Beyond#148]
### Confusion
So, I'm running a **Create: Above and Beyond** SMP and it's randomly being laggy and buggy today, yesterday I claimed a few chunks on an FTB Team, added a few loaded chunks, and logged off, and this morning when I tried to log on and try using FTB chunks the server just froze, with broken blocks not dropping, and no player damage happening at all, and then after a minute or so it randomly kicks me and the server console outputs this:
```
[Server Watchdog/FATAL] [minecraft/ServerHangWatchdog]: A single server tick took 60.00 seconds (should be max 0.05)
[Server Watchdog/FATAL] [minecraft/ServerHangWatchdog]: Considering it to be crashed, server will forcibly shutdown.
```
The same thing happens when I restart the server, and after trying it a few more times now it kicks me after a few seconds of joining, and I have no clue what to do.

I'm running the server on [server.pro](https://server.pro), all default mods and mod configs, and I have no clue what to do
Don't know if this is something with server.pro, the modpack, or just FTB, but if anyone is able to help that would be nice here's the server crash report just in case: [Gist Page](https://gist.github.com/V0ru5/1bbcd1e09ecee19f031e024d5df1b386)

Let me know if any more information is needed, my brain is imploding

**Comment by Ch1216** [comment]
Did you mess up the title?

**Comment by V0ru5** [comment]
> Did you mess up the title?

Oh yeah, sorry about that

**Comment by V0ru5** [comment]
I even tried clearing all FTB Chunk data and it still does it, no clue what's going on

**Comment by legitswitch** [comment]
post your crash report log and debug log

**Comment by V0ru5** [comment]
> post your crash report log and debug log

Crash report [here](https://gist.github.com/V0ru5/1bbcd1e09ecee19f031e024d5df1b386)
And debug log [here](https://gist.github.com/V0ru5/179a0a13e8803cf5f16a51dd75972764)

**Comment by V0ru5** [comment]
At this point as soon as I boot up the server it just closes again, so I'm going to restart the server and maybe use a different server host, also I hadn't been using the server version of the mod for the server since I didn't know that existed, so I was just taking the client sided mod stuff and putting in the config stuff, so I'll do that and use shockbyte or something
