### ISSUE TITLE
Crash on loading chunk with Holographic Planet Selector, obtained from Randomium Ore

### ISSUE THREAD

**Issue by legitswitch** [simibubi/Above-and-Beyond#155]
A user on a server was crashing after placing this block and activating it in some way. It's worth adding it to the Randomium blacklist.

![image](https://user-images.githubusercontent.com/88232383/142331800-862fbf0f-1d33-41b4-b08d-3885926363a8.png)

**Comment by scrarp** [comment]
Same problem here and people who were in render-distance or in the same dimension (we couldn't test) can't join the server now. Any solutions to this problem?

**Comment by jaypitti** [comment]
> Same problem here and people who were in render-distance or in the same dimension (we couldn't test) can't join the server now. Any solutions to this problem?

if you know the coords of the chunk you can find the MCA file and use NBTExplorer to remove them

**Comment by scrarp** [comment]
> 

I know the rough coordinates so I tried removing it with the command "/fill 510 60 680 530 50 700 air replace advancedrocketry:planetholoselector" (chunks forceloaded, should be the right block and  to replace) and it said "no blocks were filled". Is there any difference between those two methods?

**Comment by scrarp** [comment]
> 

I know the rough coordinates so I tried removing it with the command "/fill 510 60 680 530 50 700 air replace advancedrocketry:planetholoselector" (chunks forceloaded, should be the right block and to replace) and it said "no blocks were filled". Is there any difference between those two methods?

**Comment by scrarp** [comment]
> if you know the coords of the chunk you can find the MCA file and use NBTExplorer to remove them

I know the rough coordinates so I tried removing it with the command "/fill 510 60 680 530 50 700 air replace advancedrocketry:planetholoselector" (chunks forceloaded, should be the right block and to replace) and it said "no blocks were filled". Is there any difference between those two methods?

**Comment by legitswitch** [comment]
You can just open the region file in NBTExplorer, use the search function, and for value, type "planet". Then just delete the tag that appears under tile entities. Also, add the block to randomium's blacklist to prevent the issue from happening again.
