### ISSUE TITLE
Chisels and Bits, Lava, and Andesite Generation

### ISSUE THREAD

**Issue by afolk2** [simibubi/Above-and-Beyond#159]
I really liked the way the This is Create: Above and Beyond youtube video shows the andesite quarry. I couldn't figure out how the lava was just floating on top of the water without splashing over when it generated a stone. I realized after a little bit of a closer examination that it seemed as if you were using obsidian bits from C&B to keep the lava in place. When I try to duplicate this the lava flows into the adjacent blocks, despite the obsidian bits occupying that space, and then converts the entire block of air/obsidian bits into C&B lava. Hopefully this is just a mistake on my part and I'm doing something wrong. 

![2021-11-18_20 50 24](https://user-images.githubusercontent.com/24921099/142561971-24fcf36a-b320-4222-b3b6-c6951a0bcad0.png)

When I place the lava in the center of the formation it flows into the adjacent blocks like above resulting in this
Where (L) is just a block of Chisels and Bits lava

![2021-11-18_20 50 50](https://user-images.githubusercontent.com/24921099/142561983-185ca5d5-16d5-4769-b2fb-4482237592a8.png)

**Comment by afolk2** [comment]
Upon further testing this seems to be from Chisels and Bits. The liquid has to have a wall beside it that is the height of a regular block, if even 1 bit is missing then the liquid will flow out and cover the adjacent block I'm not sure if this is a feature or a bug

![2021-11-18_20 59 28](https://user-images.githubusercontent.com/24921099/142562656-115a6252-3a86-4e36-a492-fe2abc0b1bf5.png)

**Comment by Doon11** [comment]
I'm not sure why C&B is doing that, but I'm pretty sure the actual blocks used in the trailer are from CBMicroblock. Using the saw you can make simple shapes. 

![ObySlab](https://user-images.githubusercontent.com/74581824/142698116-bc706554-ef1b-49fd-b4f4-1bb9b68cc3f7.PNG)

You'll need a diamond saw to cut obsidian specifically but the iron saw and cobble will suffice if you don't have one.

![AndesiteMine](https://user-images.githubusercontent.com/74581824/142698372-afc9104c-d4c2-4278-814c-864e2c3c8931.PNG)

**Comment by afolk2** [comment]
It's probably not a bug for C&B then, I'll peruse the issues there and close it here :)
