### ISSUE TITLE
This might be me being incompetent, but... Create Texture Pack?

### ISSUE THREAD

**Issue by dudeloony** [simibubi/Above-and-Beyond#160]
I was wondering if there is a way to get the textures from this pack from Ender Storage, Advanced Rocketry, Pretty Pipes, Pipez, Metal Barrels, and Water Strainer into a separate like, texture pack or something? I understand if not, although it would be cool, you lot have already done so much, and are probably pretty busy in general. I'm very thankful for this awesome modpack, and whatever the case, have a good Thanksgiving!

**Comment by ejgibs** [comment]
if you go into the resource pack folder, there is a resource pack in there called SimiTweaks or something similar, which I assume contains all of the retexturing and would theoretically work in a different pack with the same or similar versions of mods?

**Comment by dudeloony** [comment]
> SimiTweaks

Yoooo, Thank you so much! I was running circles around myself trying to figure out how to manage this.
