### ISSUE TITLE
redstone flux cell will not output energy. it can charge itself fine but will not output to other devices. i am using invar fluxducts and it has both input and output enabled, has charge, wire is attached to an orange side and it has no redstone settings

### ISSUE THREAD

**Issue by BarrenMind** [simibubi/Above-and-Beyond#166]

**Comment by ElKameleon** [comment]
https://github.com/simibubi/Above-and-Beyond/issues/65

**Comment by BarrenMind** [comment]
> Check this, I had the same "issue". #65

put a power consumer one wire away from battery output in an isolated environment to test and did not seem to be working

**Comment by demethan** [comment]
I have the same issue.  when a cell is present in a Fluxduct network, power stops distributing to the machines. Even if the cell is not in line with the dynamos.
