### ISSUE TITLE
Chain Recipe

### ISSUE THREAD

**Issue by KiJ00** [simibubi/Above-and-Beyond#168]
The recipe for the "Chain" is overwritten by the recipe for "Iron Chain" from the mod "Forbidden & Arcanus".

**Comment by GE0NE** [comment]
Duplicate of #95

**Comment by corintho** [comment]
Fixed on 1.2:
`Fixed a recipe conflict between forbidden arcanus and ..vanilla minecraft`
Now, the recipe will craft a vanilla chain, and you can put the vanilla chain alone in the crafting grid to get 3 F&A chains
