### ISSUE TITLE
Choice between AE and RS

### ISSUE THREAD

**Issue by warplord** [simibubi/Above-and-Beyond#174]
Is it possible to be considered? Since AE is such garbage, an alternative for people who prefer RS would be very welcome.

**Comment by BeansBeefBroccoli** [comment]
AE isn't trash, but I like RS.

**Comment by Ch1216** [comment]
I feel the reason AE was added was not because of ME, but because of its chips

**Comment by Deadlock989** [comment]
It's a challenge pack. RS is for simpletons
