### ISSUE TITLE
Forbidden & Arcanus spawner scrap not dropping

### ISSUE THREAD

**Issue by ShadowMagnus000** [simibubi/Above-and-Beyond#175]
So I am attempting to make the quantum catcher from forbidden & arcanus. Attempting to break spawner to acquire the scrap with no avail on its drop. Is the spawner scrap not dropping? Is it a bug?

**Comment by gildervine** [comment]
did you try a silk touch pickaxe?

**Comment by Drakoflame** [comment]
it's a bug with F&A itself, manually update the mod fixes it

**Comment by ShadowMagnus000** [comment]
manually updating F&A fixed it, thank you.
