### ISSUE TITLE
Cherrywood Planks do not have the regular planks tag

### ISSUE THREAD

**Issue by fd347657835178** [simibubi/Above-and-Beyond#18]
Cherrywood Planks (forbidden_arcanus:cherrywood_planks) cannot be crafted into sticks or burned for fuel or used for anything but making cherrywood decorative blocks. Cherrywood Log has the minecraft:logs tag so it can be used for normal recipes, but the planks cannot be used in a normal manner, and neither can the Cherrywood Button - which means it can't be used to make cogs.

Please add tags to these items so they can be used like other wood blocks.

**Comment by Phoupraw** [comment]
And Cherrywood Log does not have the minecraft:logs_that_burn tag so it can't be smelted to charcoal.

**Comment by simibubi** [comment]
Thanks!
Plank tags and mechanical saw compatibility have been added in v1.1.
I will make a note of the charcoal issue. Maybe its worth reporting this to the mod author at this point
