### ISSUE TITLE
My no premium friend tries to join  to my LAN word and she can´t

### ISSUE THREAD

**Issue by Felimillo** [simibubi/Above-and-Beyond#189]
When I play with mi premium friends it allows them to enter to a LAN word that I´m hosting with a Tlauncher account. But when my no premium friend joins it doesn´t let her enter the world

**Comment by BD103** [comment]
I do not know how to do this through the client, but if you run a server I recommend you check out [this answer](https://gaming.stackexchange.com/a/357069).
