### ISSUE TITLE
Andesite drops andesite cobblestone even when using a silk touch tool.

### ISSUE THREAD

**Issue by garyyo** [simibubi/Above-and-Beyond#19]
Using a pick enchanted with silk touch does properly silk touch andesite, diorite, or granite (maybe others I have not tested). Silk touch works as you would expect for ores and stone.

**Comment by JDLENL** [comment]
This is a duplicate of [the report I just made](https://github.com/simibubi/Above-and-Beyond/issues/17#issue-1041797910)

**Comment by garyyo** [comment]
Seems like I lingered too long before submitting the issue.
