### ISSUE TITLE
Storage drawers icon rendering range (via drawerfps)

### ISSUE THREAD

**Issue by ivxvm** [simibubi/Above-and-Beyond#190]
There is a mod called drawerfps that prevents item icons on storage drawers from rendering when out of configured range. The default setting is 10, which is too small for anything except small closed spaces. I suggest increasing this value to something more reasonable, like 128 (8 chunks) or at least 64.

**Comment by corintho** [comment]
`drawerfps`  was removed in version 1.2 of the pack
