### ISSUE TITLE
Cannot connect to server: Tried to read NBT Tag that was too big; tried to allocate 2097156 bytes where max allowed: 2097152

### ISSUE THREAD

**Issue by jetpacker06** [simibubi/Above-and-Beyond#195]
Neither me or my friend can go near our base without disconnecting and receiving the above error. The latest client and server logs are attached
[serverlog.log](https://github.com/simibubi/Above-and-Beyond/files/7612356/serverlog.log)
[clientlog.log](https://github.com/simibubi/Above-and-Beyond/files/7612360/clientlog.log)

**Comment by BD103** [comment]
We’re you trying to deploy any extremely large schematics or pick up a Minecraft contraption with a lot of chests and items?

**Comment by jetpacker06** [comment]
> We’re you trying to deploy any extremely large schematics or pick up a Minecraft contraption with a lot of chests and items?

not at the time.

**Comment by BD103** [comment]
I looked over your logs. First, it seems like you have Optifine. This is unrecommended. (See [Tinker's Construct's view on it](https://github.com/SlimeKnights/TinkersConstruct/issues/4316).)

What I'd first do is make sure you only have mods installed with the modpack. (I also noticed the client has nbttool, try removing that as well.) Second, how much RAM does your server have? See this part of the log:

```
[27Nov2021 13:42:24.612] [Server Watchdog/FATAL] [net.minecraft.server.dedicated.ServerHangWatchdog/]: A single server tick took 60.00 seconds (should be max 0.05)
[27Nov2021 13:42:24.612] [Server Watchdog/FATAL] [net.minecraft.server.dedicated.ServerHangWatchdog/]: Considering it to be crashed, server will forcibly shutdown.
[27Nov2021 13:42:25.358] [Server Watchdog/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 233aec07-b1f7-44c6-b1fb-3752fd920949
```

You may just not have enough RAM to handle a modded server. I run a 4 GB server, and it still lags with only two players. Try these things, then get back to me! We'll figure this out.

**Comment by jetpacker06** [comment]
The problem just turned out to be a contraption, I downloaded the world and was able to run it in singleplayer. I then disabled the contraption that seemed like it would be the largest ( it was a huge multipurpose rotary farm) and reuploaded the world to the server and it has worked for a few days. Thanks for the help anyways!

**Comment by BD103** [comment]
Could I ask what the farm was for? I would like to know in case I run upon this issue again.
