### ISSUE TITLE
Serious Server/Single player issue with ChickenChunks-1.16.5-2.9.0.87-universal.jar

### ISSUE THREAD

**Issue by SeagullSeb** [simibubi/Above-and-Beyond#198]
I ran into a serious problem that was caused by using the chunk loaders from  `ChickenChunks-1.16.5-2.9.0.87-universal.jar` it was causing my server to get a "???" instead of a player count and would always time out anyone who tried to join. I eventually removed the  `ChickenChunks-1.16.5-2.9.0.87-universal.jar `mod from the server and I was able to join the server perfectly after doing alot of other troubleshooting. It seems to even mess it up if you try to load the world in single player even too because I had made a back up of the server before all the troubleshooting and I tried joining the world in a single player mode and it would `only` get stuck at 100% loading, didnt even say it was frozen either just stuck. I removed the  `ChickenChunks-1.16.5-2.9.0.87-universal.jar` file entirely from my modpack installation and am able to play the world on single player now as soon as the chunk loaders were removed.

**Comment by mr-yak** [comment]
I replicated this when I force loaded a chunk, while having a chunk loader on it. it must of got tripped up when force loading twice, and the tps dropped to 0
