### ISSUE TITLE
Planet selection crashes the game after visiting the moon; no way to return rocket to earth.

### ISSUE THREAD

**Issue by brownstein** [simibubi/Above-and-Beyond#199]
Upon completing the final questline, the player is stranded on the moon unless they packed teleportation equipment. The game currently labels Advanced Rocketry's planet selection screen as "crash game" (appropriately), and when you select earth in said screen it does exactly that.

Not sure if this is a pack bug or an advanced rocketry bug, but it'd be good to warn the player in either case - especially with the amount of time necessary to produce another guidance computer for a second rocket.

**Comment by jetpacker06** [comment]
If I know the mod right, the only other thing you should have to bring is an Earth Planet ID Chip, and you can open the rocket's menu by shiftclicking it and putting the chip in.
