### ISSUE TITLE
Game crash when breaking ProjectRed Illumination lamp

### ISSUE THREAD

**Issue by Shunigate** [simibubi/Above-and-Beyond#2]
![minecraft_LDdcFAwCll](https://user-images.githubusercontent.com/56971174/139593432-6ccbf616-4d38-4900-86b9-9c9d752fab66.png)
[crash-2021-10-31_17.36.46-client.txt](https://github.com/simibubi/Above-and-Beyond/files/7449257/crash-2021-10-31_17.36.46-client.txt)

crash works when using /fill or /setblock on the lamps too

only works with the full block variants, so not the lasers, hollow node blocks or whatever else

day or night doesn't matter, crashes regardless

same effect for inverted lamps

applies to all lamp colours too

best of luck fixing this

**Comment by simibubi** [comment]
Thanks for reporting 👍 
You can follow this issue for progress https://github.com/MrTJP/ProjectRed/issues/1684

**Comment by PlatyPew** [comment]
Inverted lamps crashing upon breaking have been fixed as of https://github.com/MrTJP/ProjectRed/pull/1698
