### ISSUE TITLE
Modpack creator's options file is included in the pack.

### ISSUE THREAD

**Issue by laserlemons** [simibubi/Above-and-Beyond#20]
The pack includes the creator's options.txt file, which sets every new user's GUI scale to 4, view distance to 13, vsync off, friendly mob sounds off, and other changes.

**Comment by therealbungus** [comment]
This is not a bug, the [Default Options mod](https://www.curseforge.com/minecraft/mc-mods/default-options) is included in the modpack.

**Comment by simibubi** [comment]
Thanks, it is indeed intended. 
But I've changed the shipped settings to be closer to a fresh install in v1.1.
