### ISSUE TITLE
Add Light Overlay?

### ISSUE THREAD

**Issue by rsaihe** [simibubi/Above-and-Beyond#201]
I think the [Light Overlay](https://www.curseforge.com/minecraft/mc-mods/light-overlay) mod would be a good quality of life addition to the pack. Without it, it is significantly more annoying to spawnproof houses from mobs (requiring you to open the F3 debug display).

**Comment by StarskyXIII** [comment]
The Haunted Bell already exists in Create.

**Comment by rsaihe** [comment]
Oh, TIL. Thank you!
