### ISSUE TITLE
Eternal Stellas Can't Be Applied to Enchanted Items

### ISSUE THREAD

**Issue by starlottemusic** [simibubi/Above-and-Beyond#207]
Tested both in survival and creative, eternal stellas cannot be applied to an enchanted item, however an item with the indestructible enchantment can have other enchantments added to it afterwards. Assuming one or the other is unintended behavior.

**Comment by BD103** [comment]
Are you running the latest version of the modpack? (Version 1.2) I remember seeing a change with the Eternal Stellas in c65c405822abfe90ce8adeb9b79a36a2c06a0865.

**Comment by Maurdekye** [comment]
This was happening to me and my friend; we discovered it was because Indestructible conflicts with Unbreaking, and the enchantment won't work if the tool already has unbreaking on it.
