### ISSUE TITLE
Cannot make stone button due to extended caves pebble recipe. This blocks other important recipies.

### ISSUE THREAD

**Issue by Elither** [simibubi/Above-and-Beyond#210]
I cannot make stone buttons as it instead makes pebbles. This blocks a few things such as the occultism storage accessor which require stone buttons. Or the reliquary hammer assembly.

**Comment by Elither** [comment]
Another related issue in that there are conflicting recipes is #204 
These could be solved by including a mod to pick between conflicts such as https://www.curseforge.com/minecraft/mc-mods/polymorph

**Comment by UristMcStoutHorn** [comment]
Tossing another recipe on there.  Boom Arrows and Explosive Arrows share a recipe.
