### ISSUE TITLE
Another Server Crash bug: Hephaestus Forge crashes server

### ISSUE THREAD

**Issue by legitswitch** [simibubi/Above-and-Beyond#211]
https://wiki.valhelsia.net/external-mods/forbidden-and-arcanus/wiki/blocks#hephaestus-forge

Hephaestus Forge from Forbidden Arcanus crashes the server when you move within ~8 blocks of it. It is formed from a multiblock structure, so not crafted.

https://www.toptal.com/developers/hastebin/orinudiyaz.properties

**Comment by ShadowMagnus000** [comment]
I have also experienced this crash and I can provide a crash report from my server. 
[crash-2021-12-03_14.30.49-server.txt](https://github.com/simibubi/Above-and-Beyond/files/7651493/crash-2021-12-03_14.30.49-server.txt)

**Comment by BigTiddyNepNep** [comment]
Replicated by accident and now I've broken our server. Please just remove this mod, it causes so many problems.
