### ISSUE TITLE
trees convert rich soil into dirt

### ISSUE THREAD

**Issue by Ciruttai** [simibubi/Above-and-Beyond#214]
saplings that have grown on rich soil immediately convert it into regular dirt.

**Comment by BD103** [comment]
Trees are not meant to grow on rich soil, only farmland. (Wheat, carrots, potatoes, etc.)

**Comment by Deadlock989** [comment]
> Trees are not meant to grow on rich soil, only farmland. (Wheat, carrots, potatoes, etc.)

Wrong.

**Comment by Ciruttai** [comment]
> Trees are not meant to grow on rich soil, only farmland. (Wheat, carrots, potatoes, etc.)

in 1.1 i had an automated spruce tree farm growing on rich soil and it never converted

**Comment by afolk2** [comment]
I also have a tree farm using rich soil right now in version 1.2 and it doesn't convert into dirt.

**Comment by Ciruttai** [comment]
try growing a cherry blossom tree on it.

**Comment by afolk2** [comment]
That may be part of the problem, I think there is another issue with Forbidden and Arcanus saplings crashing servers. Try growing just Vanilla saplings on the rich soil.

**Comment by Ciruttai** [comment]
there goes my big money idea of selling cherry tree wood, guess i'll have to sell bread instead
