### ISSUE TITLE
MultiMC cant load mods problem

### ISSUE THREAD

**Issue by oowowowowoowow** [simibubi/Above-and-Beyond#215]
java 17 with 2176 MiB max memory allocation
[crash-2021-12-02_20.06.27-fml.txt](https://github.com/simibubi/Above-and-Beyond/files/7643828/crash-2021-12-02_20.06.27-fml.txt)

**Comment by BD103** [comment]
[Create Above and Beyond does not support Java 17.](https://github.com/simibubi/Above-and-Beyond/wiki) Please go to [java.com](https://www.java.com/en/download/) and download the correct version there. (For Windows, make sure it is 64-bit!) You can configure the version of Java through MultiMC once installed.

**Comment by BD103** [comment]
See [this article](https://github.com/MultiMC/Launcher/wiki/Java-settings#java-runtime) for changing the Java runtime.
