### ISSUE TITLE
Constant Mismatched Mod Lists Error

### ISSUE THREAD

**Issue by Endrez42** [simibubi/Above-and-Beyond#22]
Installed the server entirely and ran it using forge-1.16.5-36.2.8.jar as instructed.

Installed client directly from curseforge launcher without modifying it in the slightest.

Still getting the error. Perhaps a config / kubejs has been modified on one but not the other, though using the same file on both the server and client has still resulted in a mismatched mod list.

I will attempt to see if I can get this working without mods, KubeJS or configs to see if the error is in one of the folders.

And just in case, Optifine has not been installed nor has any other client only mod. These are fresh installs using curseforge launcher to get to a server run on BisectHosting.

**Comment by Endrez42** [comment]
UPDATE: RE AUTHENTICATE CAUSES MOD MISMATCH.

Can connect to server just fine without it.

**Comment by simibubi** [comment]
I have updated some jars that had been responsible for issues similar to this. Please try again with v1.1
Cheers!
