### ISSUE TITLE
Weird glitch I found when I spawned in.

### ISSUE THREAD

**Issue by TheCubifyer** [simibubi/Above-and-Beyond#221]
![2021-12-04_13 40 29](https://user-images.githubusercontent.com/95531582/144709865-6f638902-da2e-4d1f-9855-a527f610359a.png)
![2021-12-04_13 46 53](https://user-images.githubusercontent.com/95531582/144709911-827d65fd-189e-4afa-baff-43753de77112.png)

**Comment by Nyoom-Monster** [comment]
I find these A LOT all over the ocean. It's very strange.
