### ISSUE TITLE
Ender Tank causes the depth of block entities to render at the front of everything.

### ISSUE THREAD

**Issue by sarisman84** [simibubi/Above-and-Beyond#231]
As the title suggests, looking at an ender tank causes the following effect: 
![image](https://user-images.githubusercontent.com/7117508/144933484-b321e08d-54d5-41d3-a0b0-33767eaaf75b.png)

**Comment by SOL3675** [comment]
https://github.com/TheCBProject/EnderStorage/issues/172
> Remove optifine or disable Optifine FastRenderer.
