### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by WGINC** [simibubi/Above-and-Beyond#236]
Well, the modpack crashes on startup

I am running this on a totally speced out 2020 macbook air with an M1 chip

https://pastebin.com/bnFuP2h9

**Comment by mythmon** [comment]
You're running Java 17. You need to use Java 8 (aka Java 1.8). See also #1.

**Comment by WGINC** [comment]
Switching gives me this

https://pastebin.com/3a4UjgDU

**Comment by mythmon** [comment]
That log indicates it can't find `liblwjgl.dylib`. Some quick Googling found me this: https://stackoverflow.com/questions/69457707/lwjgl-failed-to-locate-library-liblwjgl-dylib-in-intellij-idea

Are you using an M1 Mac by chance? It seems liblwjgl has problems on that platform.

It looks like some people have had success with using the official Mojang version of Java 1.8, which runs in the x86_64 compatibility layer: https://github.com/Pierce01/MinecraftLauncher-core/issues/76. I'm not sure how you could enable that though.

**Comment by enderger** [comment]
Experiencing the same issue on NixOS x86_64, using Java 8 fixed it for me (Zulu works in my case).
