### ISSUE TITLE
Looking around causes massive lag spikes

### ISSUE THREAD

**Issue by GionaCantarutti** [simibubi/Above-and-Beyond#24]
The wider the rotation of the camera the more intense the lag, up to a compleate freeze from being at a stable 60fps

**Comment by legitswitch** [comment]
I'm using 1000Hz just fine without lag.

**Comment by glektarssza** [comment]
I'm seeing this issue as well but it's not actually a problem with how quickly the game is rendering. Something about a high mouse polling rate appears to be causing the time taken to tick the world to sky rocket to over 90% of the total time consumed. My frame rate still reports as above 60 but the mod pack suffers from awful input latency and vertical tearing. Only decreasing the poll rate on my mouse seems to help this issue.

**Comment by AbiDrew** [comment]
This sounds like it would be an issue with specific mouse drivers and nothing to do with the pack or even Minecraft. Closing because it's most likely not us.
