### ISSUE TITLE
But I thought we needed the mechanical mixer...?

### ISSUE THREAD

**Issue by TJCgames** [simibubi/Above-and-Beyond#240]
In the second quest, `Preparations`, it asks for a mechanical mixer. Thing is, once you get it, it takes the mixer out of your inventory! I don't think that should happen.

**Comment by rafasoares** [comment]
It's a bug that's [fixed in version 1.2](https://github.com/simibubi/Above-and-Beyond/wiki/1.2#tweaks). Make sure you're using the latest version

**Comment by TJCgames** [comment]
why is gdl loading 1.1?

**Comment by TJCgames** [comment]
wait yep i have 1.2
