### ISSUE TITLE
Bugged Tconstruct version

### ISSUE THREAD

**Issue by Romananas** [simibubi/Above-and-Beyond#243]
The new version of the modpack has a bugged  Tconstruct version (3.3.0.308), armor doesn't have armor point / modifiers points

**Comment by Crazyabe111** [comment]
Other issue with the version: Slime boots don't bounce or improve jump height, they DO however make you immune to fall damage- and take away almost all your momentum in ALL directions when you hit the ground from farther than 1 block.

**Comment by zedle** [comment]
+1 on this, manually updated tinkers to fix this for now
