### ISSUE TITLE
Tinkers construct slime boots are gone

### ISSUE THREAD

**Issue by Mathssm** [simibubi/Above-and-Beyond#244]
Tinkers construct slime boots are gone in the new version realeased today, but slingshots are still available. So, I believe it's a bug

**Comment by Crazyabe111** [comment]
Not a bug as far as I can tell- in the Version of Tinkers the new update uses 'slime boots' are made by pouring 4 blocks of ender slime onto a rabbits foot, additionally Slime boots now have durability.

**Comment by Mathssm** [comment]
> Not a bug as far as I can tell- in the Version of Tinkers the new update uses 'slime boots' are made by pouring 4 blocks of ender slime onto a rabbits foot, additionally Slime boots now have durability.

Oh, you're right! Thanks man
