### ISSUE TITLE
Incorrect Smithing table recipe

### ISSUE THREAD

**Issue by NerdySpider** [simibubi/Above-and-Beyond#247]
hey there! just was looking through some recipes and I happened to spot a incorrect recipe. I'm not too sure why, but using a piece of netherite on this hammer seems to downgrade it to diamond, haha!
![image](https://user-images.githubusercontent.com/29170640/146387789-ef698563-b117-49c2-8ecc-8c457f7b5ea2.png)

The item in question is the "Netherite Blacksmith Gavel" and the "Diamond Blacksmith Gavel" From forbidden and Arcanus!

**Comment by quietust** [comment]
This is a bug in Forbidden & Arcanus itself, and it was apparently [fixed](https://github.com/stal111/Forbidden-Arcanus/commit/983dd37ac72367b5251c7825e27da4739cf7418f) in version **1.18.1**-2.0.1.
Unfortunately, I don't know if there are any plans to backport it to 1.16.5, so it might be necessary to fix it within this pack using KubeJS.
