### ISSUE TITLE
game crashed

### ISSUE THREAD

**Issue by GZMOSV** [simibubi/Above-and-Beyond#249]
The game crashed whilst unexpected error
Error: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:oreIron
Exit Code: -1

**Comment by GZMOSV** [comment]
[crash-2021-12-17_13.23.29-client.txt](https://github.com/simibubi/Above-and-Beyond/files/7737154/crash-2021-12-17_13.23.29-client.txt)

**Comment by BraveCaperCat** [comment]
#396 Is similar, but exit code: 1
