### ISSUE TITLE
CCL has caught an exception whilst rendering a block

### ISSUE THREAD

**Issue by S1arGazer** [simibubi/Above-and-Beyond#25]
Have been getting these messages in the chat for a couple minutes, then stumbled upon some kind of room with invisible walls, which happend to be the blocks causing the issue it seems. So i had a brilliant idea to try and break one. Well, that backfired and crashed my game. Although after hopping into the world again it seems to have fixed itself, here's a crash report anyway in case it happens again.
[crash-2021-11-02_19.10.55-client.txt](https://github.com/simibubi/Above-and-Beyond/files/7462361/crash-2021-11-02_19.10.55-client.txt)
l

**Comment by Conner-Anderson** [comment]
Do you have OptiFine installed? The CCL error occurs when it is, and you must set PlanetSkyOverride to False in  config/advancedRocketry.toml to fix it.

**Comment by AbiDrew** [comment]
As noted by Conner-Anderson this issue is not with the pack but occurs only when adding things to it that we do not test against. Closing due to not being us. But also going to pin this for other OptiFine users to find more easily.
