### ISSUE TITLE
Changelog for 1.3 says occultism was updated to 1.23.1 but still installing 1.20.1

### ISSUE THREAD

**Issue by theboo** [simibubi/Above-and-Beyond#254]
So i trying to help test an issue brought up in the occultism discord about the chimera familiar not summoning with the goat head. This was fixed in later versions of occultism. The changelog for a&b v1.3 says occultism was updated to version 1.23.1 but when you install the pack it still ships with 1.20.1.

This may have something to do with occultism adding the mc version to the version scheme recently messing with your update scripts, but unsure.

**Comment by glektarssza** [comment]
Possibly related to #252? The whole 1.3 release is... Odd.
