### ISSUE TITLE
Create Texture Bug

### ISSUE THREAD

**Issue by Pullermann124** [simibubi/Above-and-Beyond#256]
Any Textures relatet to Andesite-, Brass-, Copper-, Shadow- and Radiant Casing are Completly flat (using the Color of the Material)

**Comment by glektarssza** [comment]
Are you running Optifine with mipmapping and antialiasing turned on?

I was having the same issue and disabling both of those settings fixed it for me.

**Comment by glektarssza** [comment]
Possibly duplicate of #119
