### ISSUE TITLE
Game crashes while loading mods.

### ISSUE THREAD

**Issue by zelinux0202** [simibubi/Above-and-Beyond#257]
Hey, I'm running the latest MultiMC version on arch and I'm getting consistent crashes every  time I load the game up. [Here](https://paste.ee/p/ZVPz8) goes the log.

**Comment by glektarssza** [comment]
From your logs:

```
Java is version 17.0.1
```

Create: Above and Beyond is based on Minecraft 1.16.5 which runs on Java 8. Give it a try with Java 8 instead of 17.

**Comment by zelinux0202** [comment]
> From your logs:
> 
> ```
> Java is version 17.0.1
> ```
> 
> Create: Above and Beyond is based on Minecraft 1.16.5 which runs on Java 8. Give it a try with Java 8 instead of 17.

Thats what I was thinking yesterday night. Changed it and works!
