### ISSUE TITLE
Mismatched crude oil refining recipes

### ISSUE THREAD

**Issue by jswwww** [simibubi/Above-and-Beyond#261]
The KubeJS version of Crude Oil has a refining recipe in the Fractionating Still that is 10x the cost of the Thermal Series recipe (1000mb vs 100mb for the same output). The oil deposits in the world seem to be the KubeJS version, so this is a problem.

**Comment by demethan** [comment]
I came here to find something about this.  I have drained two oil deposits and have very little to show as end products.  This needs a review. 

Thanks.

**Comment by quietust** [comment]
The same bug seems to apply to the Blast Chiller recipes for casting digits and operators - rather than consuming 1mB, they consume 1000mB. I suspect the problem applies to _all_ Thermal recipes that take fluids as ingredients.
