### ISSUE TITLE
1.3 Blast chiller requires 1 bucket of raw logic instead of 1 mb

### ISSUE THREAD

**Issue by garyyo** [simibubi/Above-and-Beyond#264]
In 1.3 the blast chiller requires much more raw logic. This might be related to the other blast chiller issues seen in #250

In the script `kubejs/server_scripts/recipes.js` on line `2413` where it defines the recipe there is no change between 1.2 and 1.3 (it doesnt look like that script changed at all), but on 1.2 it requires 1 mb, and on 1.3 it requires 1 bucket.

**Comment by Vaevictusnet** [comment]
It would appear this is a bug in COFHCore that is already fixed, but as of right now is not yet built and published on Curse.

**Comment by quietust** [comment]
CoFH Core 1.16.5-1.4.1.8 was released a few weeks ago - its release notes mention "Fixes an issue with Fluid Ingredients", and it does indeed appear to fix the problem, though it's possible it might have other side effects.

**Comment by savelii-nechvola** [comment]
Found a way to solve problem #596 (crutch)
