### ISSUE TITLE
Any multiblock machine crashes

### ISSUE THREAD

**Issue by Ezelki** [simibubi/Above-and-Beyond#266]
Well, I was starting to make my first machine, the wood farm, and every time I tried to make any multi-block structure, the game crashed. I tried to use the cart assembler and the normal rotational force. (sorry for the english)

[hs_err_pid14148.log](https://github.com/simibubi/Above-and-Beyond/files/7772991/hs_err_pid14148.log)

**Comment by Vaevictusnet** [comment]
that's the default version of java that ships with minecraft, i think? I had good results using current adoptium at adoptium.net/?variant=openjdk8  or use whatever, just use something more current.

**Comment by Ezelki** [comment]
Thank's ! I'll try...

**Comment by Ezelki** [comment]
Do I need to turn all this on?
![image](https://user-images.githubusercontent.com/94476960/147620136-6da4e6a3-1f69-4794-99f1-2d4249c0fd08.png)
