### ISSUE TITLE
Magenta Paint Ball cannot be packed by Mechanical Press

### ISSUE THREAD

**Issue by EternalDreaming** [simibubi/Above-and-Beyond#268]
I see JEI have the Chromatic Compound receipt that using 4 Magenta Paint Ball and packing by Mechanical Press in Ver 1.2.
![image](https://user-images.githubusercontent.com/87420539/147380854-09a0c6ba-df2e-4acf-b009-2fe8567ed20d.png)
But in game this receipt cannot work, There's only can 1 paint ball inside the Basin at same time.
![image](https://user-images.githubusercontent.com/87420539/147380902-8d121061-4914-430b-9f70-377fea194e28.png)
![image](https://user-images.githubusercontent.com/87420539/147380907-990be5d9-a7bb-4f2f-99f9-942ef9b808f7.png)
I don't want to use Mechanical Crafter to do this if can because it was too bulky, so may I know how to fix this?

**Comment by Vaevictusnet** [comment]
we used the crafter, it's not that much more bulky than all the things you'd need for the basin + press.  We did have the same basin issue you did.  anyway, assuming you put the crafter above the belt you feed in the balls with, you get the whole setup in a 2x2x3 prism, including the belt.  I think that's the smallest I could make a press, if the recipe worked.
