### ISSUE TITLE
keybind problems

### ISSUE THREAD

**Issue by electricsteve** [simibubi/Above-and-Beyond#272]
i was opening my backpack and when i pushd b on my keyboard it toggled narrator and i don't know how to turn that of. i have two more problems: when i try to open map it just toggles the minimap and when i type an a in any search bar it removes all text.

**Comment by glektarssza** [comment]
The narrator settings can be found in main pause menu under `Accessibility Settings`. You should be able to turn it off from there. There's no way to unbind the key for it at this time as Minecraft itself doesn't let you do this.

For your other two issues can you provide some screenshots and a slightly better description of what's happening?

For example, please explain what steps you took to cause each issue, what you expected to happen, and what actually happened.
