### ISSUE TITLE
CANT START THE GAME 

### ISSUE THREAD

**Issue by Bano116** [simibubi/Above-and-Beyond#273]
When i try to play it it stop loading and crash idk why, pls tell me why.

**Comment by Naho-sama** [comment]
Try using forge version 36.2.21.

**Comment by glektarssza** [comment]
@Bano116 Please provide some basic information so people can help you.

Some good things to include:

* What version of the mod pack you are using
* The logs from your last attempt to run the mod pack (including a crash report if present)
* The version of Java you are using
* How much memory you're giving the game
* Any extra settings you are using with Java

This should help in figuring out what's wrong and getting you up and running.
