### ISSUE TITLE
Cannot charge the Fluxomagnet (with the charger from applied)

### ISSUE THREAD

**Issue by AstronoCraft** [simibubi/Above-and-Beyond#275]
It would be great and much more practical if we could charge the Fluxomagnet with the charger from applied energistics like we can with the entropy manipulator... For the moment, it is really complicated to just automatically charge the fluxomagnet...

**Comment by DriftinFool** [comment]
You have to use the energetic infuser from Thermal Series. A funnel with a filter set for a full magnet and to respect nbt data will pull only a charged magnet out of the charger. Not quite as simple as the AE charger that is smart enough to only output charged items, but still fairly simple solution,
