### ISSUE TITLE
Metallurgy tab on quest book has no requirements nor descriptions on the objectives

### ISSUE THREAD

**Issue by latinrev** [simibubi/Above-and-Beyond#282]
![image](https://user-images.githubusercontent.com/46919967/147839494-812088c3-7c4c-4ff4-9596-ad35f169cd1d.png)

![image](https://user-images.githubusercontent.com/46919967/147839493-9772b36b-fd05-45f6-a5cd-e4e3a02c2d99.png)

![image](https://user-images.githubusercontent.com/46919967/147839484-e204b80c-03c5-42d4-8b32-b2d8f91de750.png)

**Comment by Jorue23** [comment]
That's intended if you hover over the icon of the quests you will see numbers for example "1-3" that just explains what that processing step does with the metal and how much more you're getting
