### ISSUE TITLE
Game will crash while select destination inside rocket.

### ISSUE THREAD

**Issue by OrvilleQ** [simibubi/Above-and-Beyond#29]
## What happend
1. Create a fresh new creative mode save and start to build rocket follow the "Launching Rockets 101".
2. Clik into the rocket and select destination as moon.
3. Crash!

## Java Version
This happend both with Java 1.8 and 11.

## Logs
1.8: https://paste.ee/p/O9HYJ
11: https://paste.ee/p/H2R9m

**Comment by simibubi** [comment]
Thanks for reporting. Check out issue #8
