### ISSUE TITLE
incompatibility with occultism recipe 

### ISSUE THREAD

**Issue by NeoNo1r** [simibubi/Above-and-Beyond#296]
As it is intended the ores you mine will give the crushed version, the problem is that for the first crusher of the occultism mod (Foliot slow crusher) it needs the ore block, basically needing silk touch enchantment or similar properties for the very start of the occultism mod, the rest of the following recipes work as intended. The solution is changing the Foliot crusher recipe to other than the ore block, for example the same minerals it asks but crushed. I know is not as important as the rest of the mods but clearly the recipe wasn't left like that on purpose and is a really good quality of life change.
![capture](https://user-images.githubusercontent.com/81079887/148446941-920032cb-d81e-41bd-ab24-72d9069a8bc3.png)

**Comment by rayanth** [comment]
Additionally, the graphical depiction of the ores needed in the book (shown in OP) properly shows what is needed for the ritual, however in the Getting Started section of the book, the textual description of the ores needed still says Copper, Iron, **Silver** and Gold, rather than Copper, Iron, **Zinc** and Gold.

**Comment by rayanth** [comment]
I would like to point out, though, that you do not HAVE to start Occultism with this ritual. I've done plenty of other parts of occultism without it. All this one does is crush ores to dust, which there are numerous other ways to accomplish in the pack.

**Comment by Neouni** [comment]
The only reason you need the crusher is for crushing end stone.
You could make silk touch making rose gold (copper+gold) through create mixer and then making silk touch through tinkers.
