### ISSUE TITLE
Gradual FPS Drop with Sound Filter

### ISSUE THREAD

**Issue by RussianMeat** [simibubi/Above-and-Beyond#299]
# Describe The Bug
At first, everything seemed normal upon entering the world, where my FPS was in the normal range of 30 FPS. However, as time goes on, the FPS seems to be gradually decreasing, until the game suddenly becomes unplayable as my FPS is now hovering in the range of 1 FPS. The problem seems to fix itself after closing the instance and reloading it, but upon opening the world, the FPS still gradually reduces after a while. 
Upon opening the F3 Debug menu with pie chart, I discover that the "tick" portion is slowly increasing over time, especially if I'm in a cave and bat noise is around.
After going through the mod disabling process, I find out that Sound Filters were related to the issue.

# Reproduction Steps
1. Create new world
2. Load world
3. Open Debug Pie (Shift + F3)
4. Find a cave and create some reverb (place blocks, spawn multiple bats)
5. Idle in place for about 10 minutes while not pausing the game
6. Observe that tick slowly takes a large portion of the pie and FPS gradually drops

# Screenshots
### _Spawning in the world for a few second_
![2022-01-07_20 23 43](https://user-images.githubusercontent.com/70864933/148629272-cce42857-9940-41e1-9628-fe44fbbe23c6.png)
### Waiting in a cave surrounded by bats for 10 minutes
 ![2022-01-07_20 49 26](https://user-images.githubusercontent.com/70864933/148629319-cb220f4e-caf2-46dc-9858-43834adabd99.png)

### _Spawning in the world for a few second_
![2022-01-07_21 10 18](https://user-images.githubusercontent.com/70864933/148629688-4e9fe9b9-0375-4c8b-864d-58d5b2a4a06d.png)
### Waiting in a cave surrounded by bats for 10 minutes
![2022-01-07_21 30 42](https://user-images.githubusercontent.com/70864933/148630155-a4ff6d5b-5f92-485b-94c2-ba162fd3e6b8.png)

# Crash Report or Log
## Before disabling Sound Filter - frequent warnings with very high value
![image](https://user-images.githubusercontent.com/70864933/148629065-1ea73236-9c27-4809-a2ac-84f9a6f6d77b.png)
## After disabling Sound Filter - only occasional warnings with low value
![image](https://user-images.githubusercontent.com/70864933/148630132-3225f979-49a9-4ef9-9c14-e739028ea267.png)

# Operating System
Windows 10

# Java Version
AdoptOpenJDK OpenJ9

# Modpack Version
v1.3

# Additional Context
A similar issue appears on Sound Filters' issue page, but the author seems to be currently inactive:
https://www.curseforge.com/minecraft/mc-mods/sound-filters/issues/27

**Comment by UnderscoreKilburn** [comment]
Yup, will remove Sound Filters in the next update since there doesn't seem to be a fix for this.
