### ISSUE TITLE
Incomplete set of tags received, please contact server operator

### ISSUE THREAD

**Issue by nomisvdp** [simibubi/Above-and-Beyond#3]
My friend installed the serverpack and we all installed the modpack but when we try to join we get this error: Incomplete set of tags received, please contact server operator.

Can somebody help us?

**Comment by simibubi** [comment]
Hi, make sure to start the server using the forge-*-.jar, not the minecraft-server.jar

**Comment by benbow7** [comment]
how were you able to open the server with the forge.jar? it does nothing for me
