### ISSUE TITLE
Computer crash when loading the modpack

### ISSUE THREAD

**Issue by Str4ky** [simibubi/Above-and-Beyond#30]
I downloaded the modpack and run it once, it load, great, now when i want to load teh game with the modpack, the progressbar freeze 1 second and my whole computer shutdown instantly, any fix?

**Comment by simibubi** [comment]
Please provide a crash-report. You can find the file in the `crash-reports/` folder of your modpack installation.

**Comment by Str4ky** [comment]
Nope it's fine, it's just the new launcher and Windows 11, not your modpack and even if it's was your modpack i couldn't provide any crash report coz m'y computer will restart while the game will start loading on the launcher so before the game will even start. But works fine on the old launcher :)
