### ISSUE TITLE
Impossible to get Chisel redstone

### ISSUE THREAD

**Issue by Sarcossucus** [simibubi/Above-and-Beyond#301]
I searched any recipe to chisel a block of redstone but can't make it work. I looked but it was not like charcoal where you have to stonecut a piece of charcoal to make a "charcoal block (raw)". I've tried it with all different Chisel tools.

![image](https://user-images.githubusercontent.com/61092574/148648089-9806c703-5d7f-4964-b4e1-ac3fcf79dab8.png)

**Comment by glektarssza** [comment]
This mod pack has two chisel mods installed. One is called "Chisel & Bits" and the other is just "Chisel". This UI looks like it's from "Chisel & Bits". Try the other chisel mod.
