### ISSUE TITLE
Minecarts

### ISSUE THREAD

**Issue by ItsChase7** [simibubi/Above-and-Beyond#308]
When trying to set up lava automation with the hose pully, I have a Minecart system going back in forth between a tank I have in the overworld to the hose pully in the nether. When it through the nether the first time it works, comes back unloads the lava but when it goes back in goes past the portal instead of going through. I don't know if this has anything to do with how long it was in the overworld but I need help.

**Comment by Havaro** [comment]
What is the time between entering and leaving the Nether Portal? Vanilla mechanics do not allow entities to re-enter a portal within 15 seconds of leaving one, according to the Minecraft Wiki:

> Unlike players, other entities travel through portals instantly, and once they reach the other side, there is a cool-down time for 300 game ticks (15 seconds), in which they cannot go through any nether portals. Therefore, an entity can only travel though nether portals again, once it is not touching any nether portal for 15 seconds.

See https://minecraft.fandom.com/wiki/Nether_portal#Behavior
