### ISSUE TITLE
Molten Constantan and Bucket do not appear in JEI

### ISSUE THREAD

**Issue by Lordfirespeed** [simibubi/Above-and-Beyond#316]
Molten constantan / constantan bucket do not appear in JEI, despite being obtainable.
This is unhelpful as setting filter items using Create's filter item through JEI is possible for other alloy fluids such as rose gold, but not for constantan.

![image](https://user-images.githubusercontent.com/28568841/149601045-181633d3-30eb-49be-9cc5-361a16eadf01.png)
No constantan bucket in JEI

![image](https://user-images.githubusercontent.com/28568841/149601066-2f82bbdd-568b-417e-89ff-a743730a8ae2.png)
Molten constantan bucket

**Comment by Neouni** [comment]
It might be named different if you messed with the mod loading order or added things.
I've seen it on other people before where _volatile sky solution_ became _Liquid Obsidian_.
