### ISSUE TITLE
Failed to load 2 mods

### ISSUE THREAD

**Issue by GraphBoberIV** [simibubi/Above-and-Beyond#326]
When i launch modpack in MultiMC, an error pops up:
![image](https://user-images.githubusercontent.com/94355805/149897084-25acfd14-438a-4752-9f74-68fd1ad43df2.png)

**Comment by ChaoGirDja** [comment]
I had the same Problem, as i'am was manual switching to Java 17.0.1.
It vanished, by switching back zu 1.8.0.
