### ISSUE TITLE
JEI Cheat Mode

### ISSUE THREAD

**Issue by Threshold25** [simibubi/Above-and-Beyond#329]
I cant use JEI to look through recipes. Switching between recipes kicks me out and gives me a text saying 
"You do not have permission to use JEI's cheat mode. On this server, the following types of players can use JEI's Cheat mode: 
players who have the Operator Status (/OP) 
players who are in creative mode"

**Comment by Threshold25** [comment]
Apparently i am also unable to take loot out of chest unless i shift click the same message pops up.

**Comment by sharpskull2** [comment]
If you look at JEI next to the search bar there is a wrench icon, you can click on that to open JEI settings, in addition to that if the wrench icon is red (should be grey) that means cheat mode is enabled, you can CTRL + LMB on the icon to enable and disable cheat mode
