### ISSUE TITLE
Unable to progress in occultism due to oversight

### ISSUE THREAD

**Issue by BlindSE** [simibubi/Above-and-Beyond#33]
Since the modpack removed all recipes with ores in them, the ritual to summon a crusher spirit is impossible to complete. Some ingredients such as crushed endstone can only be obtained via said spirit ATM. This blocks most progression past golden chalk, since crushed variants of some otherwise un-processable materials are required.
![javaw_wkECzcGVzP](https://user-images.githubusercontent.com/44299163/140201153-312bfef6-c11a-4de6-b999-794dcb4281a2.png)

**Comment by simibubi** [comment]
Thanks, this is fixed in v1.1 
(I hope)
