### ISSUE TITLE
Create: Above and Beyond not working

### ISSUE THREAD

**Issue by PenguinMan1219** [simibubi/Above-and-Beyond#339]
I have tried to launch CaaB, but it does not work. I already posted this on Minecraft Forum, to get this result:

"The two mods are Forge Multipart and ProjectRed

Try other builds of this modpack:
https://www.curseforge.com/minecraft/modpacks/create-above-and-beyond/files"
However, 1.2, 1.1, and even 1.0 do not work.
Error Log:

https://pastebin.com/eeUmC1Rt

Image:
<img width="852" alt="Screen Shot 2022-01-16 at 2 11 14 PM" src="https://user-images.githubusercontent.com/82232790/150860420-6b6eb1a7-b460-4526-b674-b10ada3898f8.png">

**Comment by KeremKoksal** [comment]
Did you get it to work? I had the same problem and got it working only by disabling ProjectRed and CBMultipart. What did you do to fix yours.

**Comment by aoswalt** [comment]
According to some comments on the CurseForge page, it needs to be run with java 8. That did the job for me.
