### ISSUE TITLE
CCL Caught an exception rendering a block . See the log for info

### ISSUE THREAD

**Issue by xXt4xx028** [simibubi/Above-and-Beyond#342]
How to reproduce? just change between shaders and vanilla shaders
![image](https://user-images.githubusercontent.com/32529799/151048048-4f26c849-38e8-40a7-92af-c8f63c7a26b7.png)

**Comment by xXt4xx028** [comment]
![image](https://user-images.githubusercontent.com/32529799/151048146-924ee1e5-43ea-4715-b5eb-770be605761d.png

**Comment by Khris777** [comment]
You can disable these messages in ccl.cfg
