### ISSUE TITLE
Warning for missingno

### ISSUE THREAD

**Issue by Searith** [simibubi/Above-and-Beyond#344]
I wanted to manually make the missingno item just because it looked pretty neat, so I grabbed some crafters from storage and slapped them down to make it. Though when I picked it up it exploded most of my chests and burned a ton of my items, I went back to another backup but I ended up losing quite a lot of progress that I have to re-do. A warning somewhere about this item would be really appreciated, or even just removing the explosion since I still think its a neat item.

**Comment by WexCore** [comment]
It's unlikely that they will remove the explosion, but you can do it yourself by removing the following block of code in the `minecraft/kubejs/server_scripts/bonkers_chemistry.js` on the line 573:
``` js
onEvent('item.pickup', event => {
    let entity = event.getEntity()
    if (event.getItem().id == 'kubejs:missingno') {
        event.getWorld().getBlock(entity.x, entity.y, entity.z)
            .createExplosion()
            .causesFire(true)
            .damagesTerrain(true)
            .strength(4)
            .explode()
    }
})
```

**Comment by quietust** [comment]
In all fairness, you had to **divide by zero** in order to create Missingno, and there are multiple jokes about dividing by zero resulting in catastrophe (e.g. creating a black hole that destroys the entire planet).
