### ISSUE TITLE
Doesn't work on java 17.0.1 or Java 1.8.0_321

### ISSUE THREAD

**Issue by Jkosio23** [simibubi/Above-and-Beyond#347]
Title says it all, when I try with Java 17 I get the chickenbones errors, but when I'm on java 8 it doesn't even make a crashlog so here's the latest.log from those attempts to run on 8

 https://paste.ee/p/gv1Vt

**Comment by WexCore** [comment]
`C:/Users/tmanl/Desktop/Minecraft/MultiMC/instances/Create- Above & Beyond 1.3/minecraft`
Try removing the whitespaces from the instance folder

**Comment by Sim-ian** [comment]
I have found that trying to run it on Java 8 fails for both Client and Server, after many trials i have managed to get them both to work with Java 11.

**Comment by glektarssza** [comment]
There's currently an issue with 1.8.0_321 that causes the mod loader to crash on a reflection call. Try going back to 1.8.0_311.

**Comment by solojedi** [comment]
I ran into the same issue. Upgraded the Forge Mod Loader to 3.2.26, and now it works fine on Java 8 u321

**Comment by vidaj** [comment]
Just to add context, this was an issue with forge and java u321: https://github.com/McModLauncher/modlauncher/issues/91
