### ISSUE TITLE
Quests with rewards "Repeatable" don't work correctly.

### ISSUE THREAD

**Issue by Ethanatos** [simibubi/Above-and-Beyond#350]
When I complete quests with the "Repeatable" reward, the quests in question do not reset. All quests with this reward have the same issues.
![2022-01-30_11 27 55](https://user-images.githubusercontent.com/98698049/151703897-1829bc3d-cbe1-4dc7-a73b-6ee15b79a0aa.png)

**Comment by AxelTheModder** [comment]
I'm guessing kubejs
