### ISSUE TITLE
Enable the vanilla recipe book

### ISSUE THREAD

**Issue by ruifengx** [simibubi/Above-and-Beyond#36]
I personally prefer the vanilla recipe book (or crafting guide) button because I find it faster than searching in JEI. Sadly this button is missing in this mod pack, and I failed to locate the exact cause. I did a workspace search for the text "recipe" and "book", and tweaked some settings; I also tried removing Crafting Tweaks and FastBench, but the button just won't show up.

My current config status:

- `hideVanillaCraftingGuide = false` in `craftingtweaks-client.toml`
- `B:"Remove Recipe Book"=false` in `fastbench.cfg`

Thanks in advance for your help.

**Comment by simibubi** [comment]
Sorry for the inconvenience, for now you can re-enable the book in the following file:
`<packfolder>/kubejs/config/client.properties`
Cheers!

**Comment by ruifengx** [comment]
Thanks for the timely reply! Confirmed, this indeed fixes the problem.

Also (should have said this in advance), thanks for your great effort for making Create and this mod pack!
