### ISSUE TITLE
Wird render scale/mipmap

### ISSUE THREAD

**Issue by Spectactor** [simibubi/Above-and-Beyond#360]
Im not sure if is proble about some mod or java or forge but my game it looks like i dont use mipmap the leaves are very agressive and its not smooth i try to use optifine its same im not useing anti aliasing i use same options as other modpack i played????

**Comment by CerbonXD** [comment]
There are a couple of mods that is causing this issue apparently. I found 4 mods that are making the modpack have this issue.
-RavenCoffe - https://gyazo.com/7bab11a8d665455c439cbe48b194632e
_XkDeco - https://gyazo.com/1fba8e7d95b7d68151eefbaa3c5e0160
_MoreMinecarts
_Drinkbeer - https://gyazo.com/4b5289124a8733a480e5d6132ca1beed

**Comment by Spectactor** [comment]
> There are a couple of mods that is causing this issue apparently. I found 4 mods that are making the modpack have this issue. -RavenCoffe - https://gyazo.com/7bab11a8d665455c439cbe48b194632e _XkDeco - https://gyazo.com/1fba8e7d95b7d68151eefbaa3c5e0160 _MoreMinecarts _Drinkbeer - https://gyazo.com/4b5289124a8733a480e5d6132ca1beed

can i remove them ?? what can i lose if i do that?
