### ISSUE TITLE
Error Loading 2 Mods 

### ISSUE THREAD

**Issue by Blood00** [simibubi/Above-and-Beyond#363]
Looks Like a issue with CB multipart and project red illuminations have no clue how to fix it 

[crash-2022-02-03_21.02.29-fml.txt](https://github.com/simibubi/Above-and-Beyond/files/7999750/crash-2022-02-03_21.02.29-fml.txt)

![Crashlog](https://user-images.githubusercontent.com/11909466/152465719-d91a8636-91f8-4f24-ac07-761551a3af9e.png)

**Comment by glektarssza** [comment]
You appear to be running Java 17. Have you tried Java 8? Beware that 8u321 breaks the Forge mod loader. 8u311 is working for me at the time of writing.

**Comment by Blood00** [comment]
That worked thank you. Fresh install of my OS and MultiMC didn't even think of my java versions Thank you so much.
