### ISSUE TITLE
Freeze when scrolling over apples in hotbar

### ISSUE THREAD

**Issue by Ascanius222** [simibubi/Above-and-Beyond#364]
Singleplayer, version 1.3 of the pack. 

Bug: if I have apples in my hotbar, scrolling over them will cause the game to freeze indefinitely.

Replication: I can do this with any apples in my save. I can move the apples from the hotbar into my inventory, or toss them on the ground without issue. In either event, once they are picked up again, and scrolled over, the game freezes. No other object causes the same problem, though I haven't exhaustively tested this. The problem occurs with apples in every hotbar slot.

Other Notes:  I've tried tweaking the ram (from 8GB to 6GB) with no apparent change in the bug.

**Comment by glektarssza** [comment]
Can you please upload your game logs? That will help greatly in figuring out what what's going on. Depending on what launcher you use the logs will be inside a folder called `logs` inside the place the mod pack is installed to. The file you want to upload is called `latest.log`.

**Comment by Ascanius222** [comment]
[2022-02-04-5.log](https://github.com/simibubi/Above-and-Beyond/files/8009088/2022-02-04-5.log)
Of course, here's one of them.

**Comment by glektarssza** [comment]
Thank you for the logs!

I don't see anything immediately that would explain what's happening here. There's no obvious errors or warnings that would relate to this issue.
