### ISSUE TITLE
tinkers chunk does not load

### ISSUE THREAD

**Issue by TuKeven** [simibubi/Above-and-Beyond#366]
I had already rendered this chunk but when visiting it again in the overworld the game simply does not respond to any commands

**Comment by glektarssza** [comment]
Can you please describe your issue in more detail? Specifically, can you provide:
* how this relates to Tinker's Construct.
* exactly what you did to cause this issue (ideally as a step-by-step list).
* what you expected to happen.
* what actually happened.
* your `latest.log` file from the `logs` folder.

Thanks!
