### ISSUE TITLE
Farmers Delight Buddycard items not in JEI in 1.1

### ISSUE THREAD

**Issue by Ganpan14O** [simibubi/Above-and-Beyond#37]
It's what it says on the tin, despite having the card pack recipe again the farmer's delight buddycard items still are hidden in JEI, with the exclusion of the booster box.
![Screenshot 2021-11-04 123046](https://user-images.githubusercontent.com/85914881/140379919-6d5c1c57-718e-45a6-a86d-69d9bca9d324.png)

**Comment by MirceaZisu** [comment]
If you mean the individual buddycards 1-18, that doesn't seem like a bad choice on the modpack side. It's not like you'll do anything with them until you obtain the cards.

**Comment by Ganpan14O** [comment]
> If you mean the individual buddycards 1-18, that doesn't seem like a bad choice on the modpack side. It's not like you'll do anything with them until you obtain the cards.

No, I mean stuff like the packs and medal and such. if you look in the screenshot despite being enabled they aren't visible in jei, meaning it can be confusing for those trying to figure out how to get them, having the cards themselves WOULD be useless but that's not what I mean.

**Comment by AbiDrew** [comment]
Farmer's Delight Buddycard items are in JEI in v1.3
