### ISSUE TITLE
[Request] Add some form of handheld portable crafting table

### ISSUE THREAD

**Issue by GeorgeWL** [simibubi/Above-and-Beyond#370]
It's a feature seen in so many other packs and it does make things so much easier and improves quality of life

**Comment by quietust** [comment]
It's not quite as simple as a crafting-table-on-a-stick, but the Occultism mod's Dimensional Storage Accessor provides a 3x3 crafting grid (which is also attached to a large amount of storage, much like the Wireless Crafting Terminal mod for Applied Energistics 2 or the equivalent item in Refined Storage).
