### ISSUE TITLE
Tinker's 'Materials and you', Nahuatl and several other materials missing.

### ISSUE THREAD

**Issue by chemicalvamp** [simibubi/Above-and-Beyond#372]
I know I Heard a youtuber mention that "not every material in tinker's book (on the date of recording) was in this pack", But currently Mine only lists: wood, stone, flint, bone, necrotic bone, leather, string, and vine as the only materials listed in this pack, At first i thought they needed to be unlocked, but...

I crafted Nahuatl from youtube alone, and I can't even see the normal material stats. let alone this one. So I think if you guys went tinkering with this book, it might have gotten broke.

Great pack, appreciate ya.

**Comment by not-on-pizza** [comment]
It's in one of the later books, as it's considered to be a higher tier material.

**Comment by chemicalvamp** [comment]
The book was crafted before creating Nahuatl pickaxe and or axe head. I will craft a new book to see if it matters.

**Comment by chemicalvamp** [comment]
Doesn't matter, the book still has the same few materials.

**Comment by chemicalvamp** [comment]
Okay not-a-pizza i dont understand your thumbs down. I' just telling you what I see.

**Comment by not-on-pizza** [comment]
Nahuatl is a **Tier 3** material. It will not be listed in a book that only lists Tier 1 materials.

Perhaps you should try reading _Mighty Smelting_...

**Comment by Flabort** [comment]
What not-on-pizza is TRYING to say, is there are four books in Tinker's Construct. 5, actually.

Use JEI to see what you can craft Materials and You into, and look up the recipes from the remaining materials to make the encyclopedia - which are the other three books. There's one book for each tier of material, plus the combined book which as far as I can tell has all four books combined.

**Comment by pyroAvatar91** [comment]
I know this is an old post, but just wanted to add that, at least as of the current version in this modpack, the combined book simplifies the content from the 4 books, so it leaves out the details regarding how to set up a smeltery and foundry, and the difference between the two. Good to know if you're not familiar with how Tinkers works and need those aspects of the guide.
