### ISSUE TITLE
Additional Mod Suggestions

### ISSUE THREAD

**Issue by peanutbutterlou** [simibubi/Above-and-Beyond#373]
1. Entity Culling - This helped improve performance for me _dramatically_.
2. Redstone Pen - More fine tuned redstone lines, allowing you to manually control the direction redstone lines will travel. For example, you can make independent parallel redstone lines along adjacent blocks that don't cross over and can toggle on/off whether or not the block the line is on gets powered when the line has power.
3. Platforms - Allows the creation of more rustic or industrial bridges, staircases and walkways.
4. Glasscutter - Introduces glass stair and slab blocks (eliminating the need to use Chisels and bits)

I'm actively using all 4 of these mods in my own world without issue.

**Comment by StarsPath** [comment]
1. MrCrayFish vehicle mod - mid/end game player transportation
2. Mob Grinding Utils - for farming monster loots and generating silver coins. And absorption hoppers.
