### ISSUE TITLE
Slime boots bugged

### ISSUE THREAD

**Issue by btyrellb125** [simibubi/Above-and-Beyond#381]
When crafting slime boots, they do not have any of the modifiers and only 1 durablility, they also stop all momentum while bouncing with a slime sling.

**Comment by Neouni** [comment]
If you upgrade the slime boots or slime skulls (same issue) with anything they seem to be fixed.
I tend to throw a slotless expansion on it like a music disk for harmonious +1 upgrade or a diamond for extra stats.

**Comment by CyanKhaos** [comment]
> If you upgrade the slime boots or slime skulls (same issue) with anything they seem to be fixed. I tend to throw a slotless expansion on it like a music disk for harmonious +1 upgrade or a diamond for extra stats.

Doesn't seem to be fixed as it doesn't get it's base upgrade points (it has 5) and one ability point, it just gets 1 upgrade point from the harmonious, but it does get the durability and normal modifiers it has back
![image](https://github.com/simibubi/Above-and-Beyond/assets/110353639/fb1fced5-df77-4cf9-87c2-3e79fe7a7512)
