### ISSUE TITLE
Server wont start/create world folder

### ISSUE THREAD

**Issue by rentatank** [simibubi/Above-and-Beyond#382]
Had my server crash and then spent some time trying to work out what was causing it. Tested back up worlds and even removing world. Consistant error each time.

Attached the crash log from Console.
[Crash Log.txt](https://github.com/simibubi/Above-and-Beyond/files/8079255/Crash.Log.txt)

**Comment by Xamthos** [comment]
I had the same problem on my client. The java version you use for the server breaks some mods. Try to use an older version for your server. In my case the version 1.8.0_172 works fine.

**Comment by rentatank** [comment]
I did check the forge version however it is the current recommended version and what is shipped with the server files.

**Comment by Xamthos** [comment]
I'm not talking about the forge version. I'm talking about the Java version.

**Comment by rentatank** [comment]
I have done further testing. 4 different computers with different versions of Java all failed. However updating the server to a new version of forge fixes it.
