### ISSUE TITLE
Igneous Extruder recipe

### ISSUE THREAD

**Issue by Tom4455** [simibubi/Above-and-Beyond#387]
It seems like theres a extra unintened recipe for the Igneous Extruder
![image](https://user-images.githubusercontent.com/8618678/154826979-83a3277c-34d6-442e-8913-1c85a2c6a812.png)

**Comment by quietust** [comment]
I'm playing version 1.3 of the modpack and the above recipe is not present. Are you sure you installed the modpack correctly and didn't modify it afterwards?
