### ISSUE TITLE
Portable Storage Interface Bug?

### ISSUE THREAD

**Issue by Pel00** [simibubi/Above-and-Beyond#389]
Like in the topic... I don't know whats wrong, but I think everything i correctly placed, but why Portable Stoarge Interface when is "connected" to output does not fit evenly and does not ship items?? Take a look on the video

https://www.youtube.com/watch?v=cQ-88IUcfgc

**Comment by quietust** [comment]
The Portable Storage Interface does not _push_ items into connected inventories - you need to **pull** the items out of it using a Hopper, Chute, Funnel, or Item Pipe.

**Comment by Virinas-code** [comment]
I have the same issue, I added a funnel. Now it's transferring items right but it's still not connected graphically...

**Comment by omln** [comment]
hello, you need to put a spruce log below of the portable storage interface
