### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by BraveCaperCat** [simibubi/Above-and-Beyond#396]
**Minecraft** 1.16.5
**Forge** 36.2.20
**Modpack** 1.3
**Crash log:** 
[latest.log](https://github.com/simibubi/Above-and-Beyond/files/8190455/latest.log)
**Exit code: 1**
**Optifine** none

**Comment by BraveCaperCat** [comment]
>This crash may be caused by an invalid Java Runtime configuration.
> Check any custom configuration settings
May be the issue, but i don't know how to fix that

**Comment by BraveCaperCat** [comment]
Using java 18: exit code 2

**Comment by BraveCaperCat** [comment]
Not issue with java, Vanilla(Unmodded) works fine on 1.18 and 1.12.2

**Comment by BraveCaperCat** [comment]
Dev fix this now!

**Comment by BraveCaperCat** [comment]
Crash happens with 1.2 NOT Version specific

**Comment by BraveCaperCat** [comment]
[Mod Issue](https://github.com/Advanced-Rocketry/AdvancedRocketry/issues/2299)

**Comment by ambeeeeee** [comment]
Your behavior is absolutely unacceptable on this platform and you've made an embarrassment of yourself. If you are any older than 13 you should be insanely ashamed of your actions and immaturity.

**Comment by glektarssza** [comment]
Please do the following:
* Provide how you installed the mod pack (e.g. using a launcher and what launcher)
* Explain any modifications you've made to the mod pack or Minecraft itself
* Do not spam other issues/repositories about this. It's disruptive and rude to say the least and makes people less inclined to help you.

**Comment by glektarssza** [comment]
Also please double check your facts before making claims. This mod pack DOES use Antique Atlas as per it's CurseForge mod page. Your statement on https://github.com/Advanced-Rocketry/AdvancedRocketry/issues/2299 about that mod not being in this modpack is completely wrong.

**Comment by BraveCaperCat** [comment]
> Also please double check your facts before making claims. This mod pack DOES use Antique Atlas as per it's CurseForge mod page. Your statement on [Advanced-Rocketry/AdvancedRocketry#2299](https://github.com/Advanced-Rocketry/AdvancedRocketry/issues/2299) about that mod not being in this modpack is completely wrong.

I don't see "Antique Atlas"

**Comment by BraveCaperCat** [comment]
> Provide how you installed the mod pack

curseforge launcher

**Comment by BraveCaperCat** [comment]
> Your behavior is absolutely unacceptable on this platform and you've made an embarrassment of yourself. If you are any older than 13 you should be insanely ashamed of your actions and immaturity.

Please remove this, it's completely unrelated

**Comment by BraveCaperCat** [comment]
I'm not responding until you say sorry for saying bad things about me! >:(

**Comment by ambeeeeee** [comment]
Operating under the assumption you aren't joking about your age, please do not reveal your age on the internet while being so young. Additionally, your account violates the [GitHub TOS](https://docs.github.com/en/github/site-policy/github-terms-of-service).

Antique Atlas *is* in the pack. Hell, it even has a [configuration file](https://github.com/simibubi/Above-and-Beyond/blob/main/config/antiqueatlas.client.toml) in this very repo. 

Have you tried reinstalling the pack?

**Comment by Silfryi** [comment]
Taking a closer look at the crash report it's either that or Supplementaries, but I would not put it past a failed install to cause the error. There's definitely none of our (AR) code in the stacktrace.

**Comment by glektarssza** [comment]
> > Your behavior is absolutely unacceptable on this platform and you've made an embarrassment of yourself. If you are any older than 13 you should be insanely ashamed of your actions and immaturity.
> 
> Please remove this, it's completely unrelated and anyway i'm not 13, i'm 9, and will be 10 this year

Unfortunately you **MUST** be 13 years of age or older to use GitHub according to their Terms of Service (see [Section 3 - Account Requirements](https://docs.github.com/en/github/site-policy/github-terms-of-service#3-account-requirements)).
