### ISSUE TITLE
The modpack doesn't run

### ISSUE THREAD

**Issue by DavidGXk** [simibubi/Above-and-Beyond#400]
Hello, I start to run the modpack and the loading goes on, but when it should stop, I got an error 
![image](https://user-images.githubusercontent.com/68712135/157033381-a6002ad1-7924-4fd1-a4b6-ad48e1e03ae1.png)
 
That's log: https://paste.ee/p/aes6w
That's the crash file: https://paste.ee/p/2txYL

Java Version - 17

Thanks anticipate for help. I love so much the idea of this modpack.

**Comment by darkedone02** [comment]
I am having a similar issue.

**Comment by glektarssza** [comment]
@DavidGXk Your main log indicates you're running Java 17.

```
ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 17 by Oracle Corporation
```

This mod pack runs on Minecraft 1.16.5 which runs on Java 8. Please try changing Java versions.
