### ISSUE TITLE
impossible to make crafter

### ISSUE THREAD

**Issue by circutstream** [simibubi/Above-and-Beyond#403]
hello,i saw that to make a crafter you need brass but to get brass you need a smelter but to get a smelter you need mechanical crafters making getting crafters impossible.

**Comment by danelynnn** [comment]
I'm not sure if this is the same mod version, but in the version I have smeltery controllers use sealed mechanisms that use rubber and kinetic mechanisms (these should be obvious). which block specifically are you talking about?
