### ISSUE TITLE
The profession Quests aren't recognizing coins

### ISSUE THREAD

**Issue by Allaark** [simibubi/Above-and-Beyond#405]
Inventory:
![image](https://user-images.githubusercontent.com/92659523/158102407-bd58199e-7979-4c54-82d5-ae118887052b.png)

The trying to submit coins:
![image](https://user-images.githubusercontent.com/92659523/158102486-5928d59c-d517-47bb-9515-a1d77b939f75.png)

**Comment by UnderscoreKilburn** [comment]
Hi! You've probably fixed this by then, but just for anyone running into the same issue, you need to complete the Professions quest first by clicking the checkmark before you can buy any profession cards.
