### ISSUE TITLE
Mystical Dagger on creatures causes server to crash

### ISSUE THREAD

**Issue by Neouni** [simibubi/Above-and-Beyond#407]
Used the Mystical Dagger from _Forbidden and Arcanus_ on a bird from _Exotic Birds_ and it crashed the server.
Easily repeatable.

Edit:
Tried it on a _Minecraft_ Pig and it crashed as well, so guess it's unuseable.

**Comment by danielrello** [comment]
Im updated to Forbidden and arcanus 16.2.3 and worked. So we only need the modpack Creator to link new Forbbidden and arcanus update @simibubi . Specially for MultiMc and other platforms that can upgrade automatically or download automatically
