### ISSUE TITLE
Buddycard Medal gets consumed while combined with token

### ISSUE THREAD

**Issue by Neouni** [simibubi/Above-and-Beyond#409]
Buddymedal + token + 2 card packs should make another medal and not consume the original one.

Might be related to modpack messing things up or buddycard mod not backporting some update ?

**Comment by UnderscoreKilburn** [comment]
Looks like that recipe always had some problems, the latest version of Buddycards straight up removes it along with all mentions of medal tokens. Since the upcoming version of the modpack updates all the included mods, I suppose this can technically be considered fixed?
