### ISSUE TITLE
[Suggestion] Add FTB Backups to server (and/or client) zips

### ISSUE THREAD

**Issue by Spiker985** [simibubi/Above-and-Beyond#42]
FTB Backups is an extraordinarily useful mod, especially for server owners. I personally never play without it, and have added it to my server instance.

Figured I'd offer adding it to the modpack for future updates, as there are so many things that can go wrong with your world and FTB Backups relieves a lot of the stress about worrying about them.

**Comment by Jdewi12** [comment]
Yep just corrupted my level.dat and have no way to recover the seed (region files etc. are fine). My own fault but a backup would've saved me.

**Comment by OmaiGrundles** [comment]
This is the first modpack I've played in like 7 years that did NOT have an autobackup mod. And i had to learn this the hard way.

**Comment by AbiDrew** [comment]
This had been added in v1.2. Closing.
