### ISSUE TITLE
Computercraft Modem Recipe Conflict

### ISSUE THREAD

**Issue by Ninhydrinal** [simibubi/Above-and-Beyond#43]
Computercraft's wired modem has the same recipe as Futura (Screen Metallic) from Chisel and as such is uncraftable

**Comment by Johnystar** [comment]
Can confirm, just tried crafting a **Wired Modem** from CC and got **Futura (Screen Metallic)** from Chisel instead.

**Comment by HyJyncks** [comment]
This is the only issue I see in the pack.

**Comment by Johnystar** [comment]
> This is the only issue I see in the pack.

Cannot same I feel the same. #128

**Comment by Ictoan42** [comment]
Yep this is really causing problems, especially given that it makes it impossible to wrap inventories as peripherals for computer powered production lines without them directly neighbouring the computer

**Comment by AbiDrew** [comment]
This issue was fixed in v1.2, closing.
