### ISSUE TITLE
Charcoal can't be created by bulk blasting wooden logs.

### ISSUE THREAD

**Issue by LumberWizard** [simibubi/Above-and-Beyond#431]
A bulk blasting recipe to get charcoal from logs is missing. I suspect it's caused by Desolation's recipe to smelt charcoal into activated charcoal.

**Comment by UnderscoreKilburn** [comment]
Got it, looks like this was a conflict with Architect's Palette. For now you should still be able to blast logs into charcoal, the recipe still works despite not showing up in JEI.
