### ISSUE TITLE
Release this modpack on modrinth

### ISSUE THREAD

**Issue by Arbee4ever** [simibubi/Above-and-Beyond#435]
Hey, I already talked a lot about this on Discord.
Now here's an issue for that:

modrinth is a new open source mod hosting platform with an open api for everyone to use.
They recently added support for modpacks (only in beta as of now though) and support mod source links from 
![image](https://user-images.githubusercontent.com/45911516/169087709-e8148c84-22cd-4310-937d-e69338338881.png)
Source: https://docs.modrinth.com/docs/modpacks/format_definition/#downloads

modrinth already has a big community and are working with multiple launchers to bring support for modrinth packs to them.

**Comment by TheGlitch76** [comment]
https://blog.modrinth.com/modpack-changes/

**Comment by AbiDrew** [comment]
I figured. This will be too much work now. This could be explored later on, but now is not a good time for it.
