### ISSUE TITLE
Optifine is not working

### ISSUE THREAD

**Issue by CrunchyGaming** [simibubi/Above-and-Beyond#436]
Modpack description says that optifine works however everytime i try to launch the modpack, I can't even load into the menu because it just freezes. If i remove optifine it works again. Please fix optifine support.

**Comment by glektarssza** [comment]
Optifine is not officially supported, as per the modpack description.

![image](https://user-images.githubusercontent.com/94402525/169104318-6ba921ef-aaf8-4a24-a4f4-5d7f4378cf69.png)

If you could provide a log file from the last time you launched the pack with Optifine installed it might be possible to help you. As it stands there's not enough information to offer any concrete help.

**Comment by AbiDrew** [comment]
This issue is likely interrelated to Issue #25 and is now marked as a duplicate. For anyone with Issues with OptiFine, be aware it's not officially supported. Closing as this is not our issue.
