### ISSUE TITLE
Loading world crashes the game

### ISSUE THREAD

**Issue by Adubio** [simibubi/Above-and-Beyond#439]
When I try to load one of my worlds, it decides to crash while it's stuck on the "Reading world data" in the loading process. I tried loading a copy of it and try creating a new world, both of which failed and crashed my game. I do get this code: "-805306369" but haven't been able to find out what it means.

I have tried:

- restarting my PC

- re-logging in my MC account

- repair profile in Curseforge 

- adjust settings on allocating memory

None of this has worked

**Comment by AbiDrew** [comment]
please attach as a file your latest.log and debug.log

**Comment by Adubio** [comment]
Are these the right files?
[debug-1.log.gz](https://github.com/simibubi/Above-and-Beyond/files/8758291/debug-1.log.gz)
[2022-05-22-9.log.gz](https://github.com/simibubi/Above-and-Beyond/files/8758294/2022-05-22-9.log.gz)

**Comment by AbiDrew** [comment]
It looks like missing or corrupted mods. Sometimes repair does not fix these. Try removing the instance and re-adding. You said you are using the Curseforge launcher from Overwolf? So it's not the API change if so. Your world save might be recoverable, check Minecraft wiki how to save that and put it in a new instance if you don't know how. It could also be broken though.

**Comment by Adubio** [comment]
So, I just saved my world now, and have gotten a new instance, but for some reason, when I try to make a new world or open my old world, it still doesn't work, it even has the same Exit Code "-805306369"

**Comment by AbiDrew** [comment]
You seem to misunderstand. You need to delete the entire instance after backing up your save data, and then reinstall the instance through your launcher clean. You can then attempt to add your old world to the new instance. This is assuming you're using CurseForge Launcher for Overwolf or ATLauncher, because currently those are the only launchers that are functioning for CurseForge modpacks.

**Comment by Adubio** [comment]
Yep, I've done that, I should've specified, gone into instances folder, and deleted the whole pack. and to be sure I did it all again, I even made a new world before I bothered putting in my old one to test it out. NOPE!
same Exit Code, right when loading the world, even when I deleted the whole folder and Installed clean off curseforge, thrice, so either I believe my computer is causing the issue somehow, or curseforge is screwing up the modpack.
I am honestly stumped at this point

**Comment by AbiDrew** [comment]
Oh. You're installing the pack instances manually off the site? This could be a java version compatibility issue then. Are you using the Mojang/MS official launcher?

**Comment by Adubio** [comment]
Yes, I am using the official minecraft launcher. But since you mentioned Java, should I try updating it?

**Comment by AbiDrew** [comment]
I would try to specifically install openjdk release 1.8.0_u312. Neither newer or older than.

**Comment by Adubio** [comment]
Ok, how do I do that?

**Comment by AbiDrew** [comment]
Install this file: https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.msi

**Comment by Adubio** [comment]
Alright, now do I just boot up MC and see if things work now?

**Comment by AbiDrew** [comment]
Yup.

**Comment by Adubio** [comment]
Alright, it works!
I loaded up a new world and the issue is resolved!
But I probably can't save my old world, since I tried that and had to delete n' download another instance to get back to the unbroken state.
But, I'm just happy to be playing again

**Comment by Adubio** [comment]
The problem is back at it again

**Comment by Adubio** [comment]
Nevermind, just had to repair the java Version, I guess I have to keep that in check
