### ISSUE TITLE
Fertile Soil bug?

### ISSUE THREAD

**Issue by Vashta** [simibubi/Above-and-Beyond#444]
i was using fertile soil in my automated tree farm which uses origin saplings i noticed when the sapling turns into a tree it turns the fertile soil into regular dirt which it shouldnt be doing ive used it before in several packs and it kept the soil

**Comment by UnderscoreKilburn** [comment]
This is a known issue from Biomes O' Plenty, it only happens with certain trees and there isn't much we can do to fix it, unfortunately. It only seems to happen with oak-like trees (i.e. cherry, jacaranda, origin, rainbow birch) so best to avoid using those in your tree farms.

**Comment by AbiDrew** [comment]
It looks like it's probably related to https://github.com/vectorwing/FarmersDelight/issues/110

It's marked as closed there, but if you follow the chain it was closed upstream in a 1.18.2 release, with no planned back-port to 1.16.5.

We have no control over this, sadly, go ask vectorwing to back-port the fix from 1.18.2 to 1.16.5, and once a release is pushed fixing the issue we'd be happy to include the updated mod.
