### ISSUE TITLE
Broken textures for layered gabbro, normal and vertical gearboxes

### ISSUE THREAD

**Issue by Bekkytt** [simibubi/Above-and-Beyond#452]
There may be more broken textures, but these were the three I've found.
![image](https://user-images.githubusercontent.com/107440075/173450699-4d91b2a5-3e48-4b37-b5d2-17cc8943d9ab.png)

**Comment by AbiDrew** [comment]
Are you using any performance mods like OptiFine or magnesium?

**Comment by Bekkytt** [comment]
I was able to fix it. Magnesium works, it was Helium that was the problem.
