### ISSUE TITLE
Game crashes while booting up

### ISSUE THREAD

**Issue by Adubio** [simibubi/Above-and-Beyond#453]
The crash report says it happened while rendering the overlay, and has the exit code: -1, and I've tried to load three times.

This started happening when my game crashed while I was playing on a server, with the exit code: 1

here's the crash report
[crash-2022-06-21_14.44.23-client.txt](https://github.com/simibubi/Above-and-Beyond/files/8952777/crash-2022-06-21_14.44.23-client.txt)

**Comment by Adubio** [comment]
Uh, hello? I think I've been waiting two days at this point

**Comment by AbiDrew** [comment]
Looks like it wiped out part of your configuration files somehow. Only way to fix this would be to delete and re-download the instance. This isn't our issue regardless.
