### ISSUE TITLE
shaders make create blocks white or randomly colored

### ISSUE THREAD

**Issue by bebebbebbbbe** [simibubi/Above-and-Beyond#456]
I installed rubidium and oculus to the pack, made a world, and enabled some shaders but blocks from create were white or unaffected by light or had some random colors depending on the shader. I would have thought that shaders didnt work with the pack, but I saw people play with shaders and having no problems. I did the /flywheel backend off, that just made things invisible and changed nothing. help.

**Comment by AbiDrew** [comment]
This is an issue with the mods you are adding and not with the mod pack. For help from other users who have tried similar things to what you are trying and may have had varying levels of success, you should try using the discord.
