### ISSUE TITLE
Crafting Conflict between Chisels and Bits and Farmer's Delight

### ISSUE THREAD

**Issue by TinedCircle1744** [simibubi/Above-and-Beyond#48]
There is a crafting conflict between Chisels & Bits and Farmer's Delight. The Chisel and the Iron Knife are crafted the same way. The knife overrides the Chisel. I removed the Farmer's Delight mod, crafted the chisel and then loaded the Farmer's Delight mod back in and crafted the knife. This was tested on two separate computers using two separate worlds.

**Comment by simibubi** [comment]
Is this on pack version 1.1?

**Comment by TinedCircle1744** [comment]
This is the 1.0

**Comment by TinedCircle1744** [comment]
I just noticed that there is a newer version - I did not know there was a newer version. I just downloaded this a couple of days ago so I guess I did not think there would be an update so fast. I will update it and see if that helps.
