### ISSUE TITLE
Not able to import modpack from ZIP in MultiMC

### ISSUE THREAD

**Issue by andrewlalis** [simibubi/Above-and-Beyond#497]
I get the following error:
> Archive does not contain a recognized modpack type.
![image](https://user-images.githubusercontent.com/9953867/202907924-9976a5d0-80f5-4226-969e-f5701eb7a36d.png)

**Comment by tyrope** [comment]
That's an issue between CurseForge and MultiMC; something about CurseForge's ToS? Details [here](https://multimc.org/posts/0-6-16-update.html)
