### ISSUE TITLE
Crashing when Launching the Game

### ISSUE THREAD

**Issue by redkittty** [simibubi/Above-and-Beyond#503]
So whenever the FML Early Loading Process gets done the game automatically exits with Code 1

Logs: https://pastebin.com/xpwHF82D

(btw I found the solution and for anyone else having this issue then update forge)

**Comment by funkkiy** [comment]
Same issue here.

**Comment by quantumicrowave** [comment]
Same here

**Comment by quantumicrowave** [comment]
I had a similar issue and fixed it updating forge, you might try to do the same

**Comment by redkittty** [comment]
> I had a similar issue and fixed it updating forge, you might try to do the same

Oh it worked, thx
