### ISSUE TITLE
Cinnabar cannot be milled

### ISSUE THREAD

**Issue by jomnik42** [simibubi/Above-and-Beyond#504]
Edit/Solved: I was playing on a server and the server did not have the updated recipes for the modpack!
If you have this problem you can copy the server scripts files from the forge instance (in the kubejs folder) and paste them into your server script files.

I've been playing this modpack for a bit and I read that cinnabar needs to be crushed or milled in order to obtain redstone. I tried milling redstone with the Create mill and that hasn't worked.

**Comment by Starmania** [comment]
Close the issue if solved
