### ISSUE TITLE
Error joining server: "incomplete set of tags received from server"

### ISSUE THREAD

**Issue by TinyBouldr** [simibubi/Above-and-Beyond#52]
A friend and I are trying to get a server set up for us to play this modpack (version 1.1) on. Connecting to the server seems to work at first but then yields the error message "Incomplete set of tags received from server. Please contact the server operator." This problem did not occur in a vanilla server we hosted, and google searches point towards the problem being caused by inconsistency between the server and client mods.

**Comment by Geartwo** [comment]
You most likely started the "minecraft_server.1.16.5.jar" but you have to start the "forge-1.16.5-36.2.8.jar" (And if you have so you should delete the world folder bevore startup or else the mod blocks dont generate in the existing chunks)

**Comment by TinyBouldr** [comment]
Oops, my bad. It works now. Thanks!
