### ISSUE TITLE
Recipe conflict between "Charcoal Bit" [Desolation] and "Charcoal (Raw)" [Chisel]

### ISSUE THREAD

**Issue by ArchOwlen** [simibubi/Above-and-Beyond#57]
Current Result:
Input: Charcoal 
Default Output: Charcoal Bit (From Desolation)

Was Desired Result:
Charcoal (Raw) (From Chisel)

(Mods I have added to the pack should not affect this)
![image](https://user-images.githubusercontent.com/69368336/140617860-50faee36-bfe6-46ed-9571-0f138c8e9a9e.png)

![image](https://user-images.githubusercontent.com/69368336/140617754-88344ed4-acdd-407a-bb91-07632be3fd79.png)
![image](https://user-images.githubusercontent.com/69368336/140617765-11d7881c-a03c-4321-9408-2e45144df785.png)

(I personally would suggest adding Polymorph, but should be a simple fix nonetheless)

**Comment by UnderscoreKilburn** [comment]
Was fixed in 1.2, closing this.
