### ISSUE TITLE
occultism wormhole crashes server

### ISSUE THREAD

**Issue by DarkKryU** [simibubi/Above-and-Beyond#58]
When using the stabilized wormhole  to access occultism storage far away, the server crashes when shift-clicking, with this crash message.
![image](https://user-images.githubusercontent.com/93837723/140619346-95b2035f-c26c-46a3-881d-327e2458c858.png)

The mods I use are the default modpack (version 1.1) + optifine.
The server specs are:

shared AMD Ryzen 5 3600 
6GB ddr4 
1.1 modpack version
startup flags: -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true

**Comment by BlindSE** [comment]
Can confirm, server admin here. [Here are the crash logs.](https://github.com/simibubi/Above-and-Beyond/files/7491023/crash-2021-11-06_18.38.48-server.txt)
If you need any other details, please just tag me.
