### ISSUE TITLE
Mods Failed to load

### ISSUE THREAD

**Issue by OWNEDGAMING** [simibubi/Above-and-Beyond#6]
right on startup after forge loads all mods i get greeted with a screen saying 2 mods failed to load

[crash-2021-11-01_03.06.22-fml.txt](https://github.com/simibubi/Above-and-Beyond/files/7450329/crash-2021-11-01_03.06.22-fml.txt)
[latest.log](https://github.com/simibubi/Above-and-Beyond/files/7450332/latest.log)
![Create-above-and-beyond-crash](https://user-images.githubusercontent.com/59829498/139612021-4fe7dd29-6007-449f-adf8-b8b021bafde9.PNG)

**Comment by MichaelSixtyFour** [comment]
Having the same issue, seems to be from cb_multipart

**Comment by MichaelSixtyFour** [comment]
Changed to Java 8 from Java 16 and it's working now

**Comment by bevilp** [comment]
Getting the same issue, can't run the modpack.

[crash-2021-10-31_22.58.42-fml.txt](https://github.com/simibubi/Above-and-Beyond/files/7451008/crash-2021-10-31_22.58.42-fml.txt)
[latest.log](https://github.com/simibubi/Above-and-Beyond/files/7451009/latest.log)

**Comment by Meatshackles** [comment]
Same issue as well. On java 17.

**Comment by simibubi** [comment]
Yup. This pack will launch best with Java 8 (1.8.x)

**Comment by OWNEDGAMING** [comment]
i've tried it with Java 8 and i still get the same error
