### ISSUE TITLE
Vanilla iron chains reciple clash with F&A iron chains

### ISSUE THREAD

**Issue by LeoBeliik** [simibubi/Above-and-Beyond#60]
Both have the same recipe and F&A chains takes priority, besides the decorative use the vanilla chains have, they are also use as thinker's modifier.

![chains](https://user-images.githubusercontent.com/11804768/140623842-87d66446-f2a1-481c-b210-f17be403ce3f.png)

**Comment by UnderscoreKilburn** [comment]
Fixed in 1.2
