### ISSUE TITLE
Advanced Rocketry items don't have a recipe or a use

### ISSUE THREAD

**Issue by Sgambe33** [simibubi/Above-and-Beyond#62]
Hi, I installed the modpack on my server and on my client but I noticed that some of the machines from rocketry can't be crafted and some ores from lib vulpes don't have use. Is it a client bug or a server one?

**Comment by Alicegamergirl** [comment]
neither, its intentional

**Comment by Sgambe33** [comment]
> neither, its intentional

then why add it to the game?

**Comment by Alicegamergirl** [comment]
> > neither, its intentional
> 
> 
> 
> then why add it to the game?
> 
> 

Essentially, mod authors sometimes make OP items, with unbalanced recipes. Modpack authors, among other things, alter the recipes to create a more rewarding, progressive experience. And oftentimes they'll remove stuffs that's simply too OP, or doesn't fit in with the rest of the mods. Also Advanced Rocketry being in alpha I believe, has a lot of bugged items, hence justifying their removal. Hope that clarifies stuff for y'a
