### ISSUE TITLE
[1.1] All parts and tools of tinkers construct are showing as white

### ISSUE THREAD

**Issue by TechnicalEACS** [simibubi/Above-and-Beyond#63]
All parts and tools of tinkers construct are appearing as white, not the color they should be, this bug started to appear after upgrading to version 1.1. 
Image to show the bug:
![image](https://user-images.githubusercontent.com/45494086/140632091-ef4307f6-1344-4ebe-8ac6-ac139fab1513.png)

**Comment by ElKameleon** [comment]
Do you have Magnesium installed? This is likely the cause. (it was for me, also listed as an issue on magnesium's page)

**Comment by TechnicalEACS** [comment]
Would this magnesium mod be a sodium based mod?
I am using the halogen mod.

**Comment by TechnicalEACS** [comment]
Yes, that was it, I disabled the mod and the bug disappeared.
Thank you for your help.
