### ISSUE TITLE
Invar Fluxducts do not connect to Redstone Flux Cell

### ISSUE THREAD

**Issue by ElKameleon** [simibubi/Above-and-Beyond#65]
Invar fluxducts connect dynamos and redstone flux cells just fine, but if you go redstone flux cell>fluxduct>item receiving power, no power is sent, even with correct setup of sides on flux cell. This works: Dynamo>fluxduct>item receiving power... Maybe i'm using it wrong?
<img width="600" alt="issue" src="https://user-images.githubusercontent.com/25694405/140652267-99561d8a-81f5-4832-beb7-75569062ddad.png">

**Comment by AxelTheModder** [comment]
Use a Crescent Hammer on the RF Cell.

**Comment by ElKameleon** [comment]
This was fixed by shift+right-clicking the pipe closest to the power source with a crescent hammer. Thanks again!
