### ISSUE TITLE
Crashing on macOS after game window (red) launches

### ISSUE THREAD

**Issue by ViaBeans** [simibubi/Above-and-Beyond#7]
When opening the pack, it opens to the red window and crashes upon doing a deep scan of the mods available

https://pastebin.com/WURYF03Y

Here's a pastebin of the AT Launcher log.

**Comment by simibubi** [comment]
It looks like the paste was deleted before I got a chance to check it out. Feel free to re-open this with a new paste.
Otherwise I can recommend double-checking that you are using Java 8 as opposed to more recent versions.
