### ISSUE TITLE
SIlver Ingot is Currently Unobtainable

### ISSUE THREAD

**Issue by Mouy07** [simibubi/Above-and-Beyond#70]
As the title says, the silver ingot cannot be obtained. The 2 types of silver ore cannot be smelted, crushed, or processed in any way. This is an issue because the Tier 2 Dimensional Storage Stabilizer and Summon Wild Hunt Ritual require silver blocks. Also the only way to obtain silver ore seems to be with the Ore Miner Djinni. That also has some issues which I will report in a separate ticket.

**Comment by tukib** [comment]
unsure if this is the *intended* method, but you are currently able to get silver by melting silver coins

**Comment by MirceaZisu** [comment]
That is the easiest way to as well,, but nice catch.

**Comment by GE0NE** [comment]
Additionally, silver ingots can be obtained through the Test of Patience reward
