### ISSUE TITLE
Mechanical crafters placed by schematicannons cause a crash in multiplayer.

### ISSUE THREAD

**Issue by Lukea153** [simibubi/Above-and-Beyond#73]
How to repeat
1: Host a multiplayer game
2: Use and place a schematicannon blueprint containing a mechanical crafter
3: Use the machine containing the crafter.
4. The game should crash on the crafter being used.

**Comment by ElKameleon** [comment]
Can confirm, had the same issue happen to me.

**Comment by UnderscoreKilburn** [comment]
This was fixed in Create 0.3.2g, closing this!
