### ISSUE TITLE
Suggestion: switch out `Hwyla` with `The One Probe` or similar

### ISSUE THREAD

**Issue by Quezler** [simibubi/Above-and-Beyond#76]
It (or an addon for it?) can show the contents of blocks when you hold shift, here is a screenshot in enigmatica 6:

![2021-11-08_08 48 22](https://user-images.githubusercontent.com/3179271/140704012-b8ed6247-54e0-4806-8755-8b763bfafcc2.png)

i find it really annoying to not be able to shift-look at e.g, the mixing basin to see input/output item progress, or e.g. to look at a belt or depot with sticks & cobble but not knowing their stack size until i pick it up manually.

if it's already possible with a config setting somewhere in this modpack i would love to know, swapping mods is optional.

**Comment by notnotmelon** [comment]
+1

**Comment by cking** [comment]
I suggested using jade instead ( #81) - it is a spiritual and api compatible successor.

But top is good as well.
