### ISSUE TITLE
JEI Config Button does nothing, "Configured Mod" required, yet already installed

### ISSUE THREAD

**Issue by MorphZzOW** [simibubi/Above-and-Beyond#79]
The JEI Config button in the bottom right of the inventory (the wrench button) doesn't open the config menu, and instead puts in the chat "Install the "Configured" mod to access the in-game config."

Upon going to download/install said mod, it says it's already there, same version and everything. Am I doing something wrong, or is the wrong version of Configured installed?

**Comment by cking** [comment]
as a work around, you can open the config screen in the mainemu when you click the mods button.

not a solution, also I think it's more a general mod problem and not the packs fault. Haven't checked though

**Comment by GarethCarew** [comment]
It's and issue on JEIs side. If you update to the most recent version it should fix it.

**Comment by KapsiF** [comment]
Still issue is still in 1.19.2 Fabric

**Comment by Koyoinu** [comment]
Issue is still in 1.20.1 Fabric

**Comment by ArdaKaykac** [comment]
I figured it out. Just click the recipe book. 
Only than will the mod start displaying the recipes.
I hope this is helpful.










So this is how it feels to know something that other people don't...
:)

**Comment by Cloudninjakip** [comment]
> I figured it out. Just click the recipe book. Only than will the mod start displaying the recipes. I hope this is helpful.
> 
> So this is how it feels to know something that other people don't... :)

This is completely irrelevant to this issue, stfu

**Comment by YeahImRose** [comment]
Issue still persists on 1.20.1 versions

**Comment by Neamow** [comment]
Still present on 1.20.4 version.

**Comment by ejoel6781-wq** [comment]
Only thing i know how to enable cheat mode is by binding a key in options
