### ISSUE TITLE
Planet Selector UI crashes game

### ISSUE THREAD

**Issue by thompson937** [simibubi/Above-and-Beyond#8]
### How to reproduce
- Build a simple rocket
- Using the planet selector or the rocket itself open the map screen
- Click on any button (I haven't tested all of them)
- Crash?

### Crash log
![mapscreen](https://user-images.githubusercontent.com/53794179/139652750-7132a995-33ae-4f27-911c-b7a004821bcd.png)

Additional observation: Reloading the map where this incident occurred takes far longer than usual

**Comment by simibubi** [comment]
Thanks for the report, this is an issue with the Rocketry mod: https://github.com/Advanced-Rocketry/AdvancedRocketry/issues/2117
As a workaround we added recipes for Planet ID chips with destinations already set in their nbt. Cheers!

**Comment by DAmNRelentless** [comment]
> Thanks for the report, this is an issue with the Rocketry mod: [Advanced-Rocketry/AdvancedRocketry#2117](https://github.com/Advanced-Rocketry/AdvancedRocketry/issues/2117) As a workaround we added recipes for Planet ID chips with destinations already set in their nbt. Cheers!

There seems to be an issue with the Advanced Rocketry config as well. Looks like it can't be parsed properly so every time you start the modpack, it will create a new backup file of the config.

**Comment by youchen624** [comment]
crashed!!!!

[crash-2022-01-28_18.01.25-client.txt](https://github.com/simibubi/Above-and-Beyond/files/7957664/crash-2022-01-28_18.01.25-client.txt)

**Comment by AbiDrew** [comment]
@youchen624
You are using OptiFine, which is not officially supported. There is a different pinned issue with a workaround though that might get it working anyway.

**Comment by kungpoo363-sys** [comment]
นาน
