### ISSUE TITLE
Tinkers' Construct Luck doesnt work for Crushed ores

### ISSUE THREAD

**Issue by TaddelNunzn** [simibubi/Above-and-Beyond#82]
As stated in the title the Luck, Luckier and Luckiest modifiers from Tinkers' Construct don#t work on ores that drop the crushed version of themselves (Iron, Copper, ...). It works fine with all the ores that don't drop a crushed ore (Diamonds, Cinnabar, Lapis, ...)

**Comment by LeoBeliik** [comment]
It does work, I tested it in 1.1 and gives 1-2 crushed ores as it should.

**Comment by TaddelNunzn** [comment]
Oh okay, then i guess I was just pretty unlucky mining like half a stack and never getting double ore.
Thanks for testing and confirming it does work.
