### ISSUE TITLE
Indestructible enchantment has no effect on Sediment Strainer

### ISSUE THREAD

**Issue by GE0NE** [simibubi/Above-and-Beyond#85]
Applying Indestructible to a Sediment Strainer (using an Eternal Stella) for use in a Strainer Base still uses the durability and eventually breaks the Sediment Strainer after 300 uses. 

If the Sediment Strainer is removed from the Strainer Base at any point before it breaks, then its durability returns to full. This process unfortunately cannot be automated.

![unknown](https://user-images.githubusercontent.com/25130343/140880785-22bac5a2-2a8c-409d-9371-3abfeabaf17e.png)

The same is true for all the strainers added by the Water Strainer mod.

**Comment by opticGT** [comment]
indestructible only works for things in your player inventory

**Comment by GE0NE** [comment]
> 
> 
> indestructible only works for things in your player inventory

The quest book offers multiple indestructible-enchanted items intended to be used in machine inventories, like the indestructible saw and screwdriver, among others.

**Comment by ejgibs** [comment]
Is this issue going to be fixed? The Eternal Stella was so expensive to just be wasted...

**Comment by IdioticProphet** [comment]
+1 to initial. Important fix as early-game non-shop clay automation isn't possible without it.
