### ISSUE TITLE
[Inconsistancy] Crate of Apples isn't sellable through the trade station

### ISSUE THREAD

**Issue by GE0NE** [simibubi/Above-and-Beyond#86]
All of the Farmer's Delight food crates (Carrot Crate, Potatoes Crate, Cabbage Crate, Onion Crate, Beetroot Crate, etc) can be sold through the trade station for 1 silver each, however the Thermal Series Crate of Apples cannot be sold despite having the same 9 apples per crate recipe.

**Comment by UnderscoreKilburn** [comment]
1.2 added an apple crate trade, closing this now.
