### ISSUE TITLE
Server in infinite loop

### ISSUE THREAD

**Issue by drufle** [simibubi/Above-and-Beyond#88]
When I run the server for 1.1, the server console infinitely tells me that the advancedRocketry.toml file isn't correct, and that it tries to correct it, but it fails to do so and instead just attempts this process every 3 seconds or so. It doesn't seem to be stopping much from happening yet, but it's causing undue strain on my processor. Any ideas?

**Comment by Trnrr** [comment]
Download/unzip the server files again and compare the file.

**Comment by drufle** [comment]
A compare check shows that a newly-downloaded version of the toml file is identical to the one in my server's folder.
[advancedRocketry.txt](https://github.com/simibubi/Above-and-Beyond/files/7516175/advancedRocketry.txt)
Here's a .txt version of the file, if that helps.

**Comment by Trnrr** [comment]
Can you upload the log to gist or pastebin? Have you tried reuploading the server files? Are you using java 8

**Comment by drufle** [comment]
https://pastebin.com/i2MrC2cQ Here is the log of the error- that last line with the .toml file constantly correcting is what I'm referring to, it repeats that line every 3 seconds or so. I am on Java 8 and JDK 15.0.2- I haven't tried reuploading the server files yet, I can try that.

**Comment by DAmNRelentless** [comment]
That seems to be an issue with the current version of the modpack because of the version of Advanced Rocketry it's using.
This also happens client-side and is the reason for all the backups of the config which are created on each modpack start.

**Comment by Marrowisp** [comment]
I downloaded the server pack that was updated 3 days ago, but I am also having this issue, It appears someone else is also having this issue; See issue #180
