### ISSUE TITLE
Ores should have a JEI description tab for y values

### ISSUE THREAD

**Issue by rowanthemodder** [simibubi/Above-and-Beyond#9]
See title, it's a commonly asked question and a JEI tab would save rummaging through files for advanced players or just guessing and praying for most.

**Comment by legitswitch** [comment]
I noticed this too and found out Just Enough Resources adds this. You can install it on your client without requiring the server to have it.

**Comment by simibubi** [comment]
Thanks for the suggestion, I've added item descriptions to ores in v1.1
