### ISSUE TITLE
Unable to produce rose gold in mixer?

### ISSUE THREAD

**Issue by Catzador** [simibubi/Above-and-Beyond#92]
Was trying to create rose gold in a mixer by mixing gold and copper, mixer was at 32rpm, and it just wasn't mixing them. Thought it might have been an rpm issue so i boosted it to 64rpm and still wasn't working. Went into a creative world and it worked fine with only 32rpm, so I have no idea why it wasn't mixing
![image](https://user-images.githubusercontent.com/41758049/141045201-8e4b26d4-c975-4a7b-8b89-517c18c7a463.png)
![image](https://user-images.githubusercontent.com/41758049/141045179-da40da2b-1322-4aac-8662-3c9f227494bc.png)
Edit: Thinking about it, I had a filter on it and then took the filter off to make it, could it have not worked because there was a filter on it at one point? There is no filter on it in the screenshot

**Comment by OmaiGrundles** [comment]
You likely have the mixer outputting to a chute. 

If the recipe outputs a fluid, it seems to only start the recipe if:
A: the basin outputs to nothing
B: the basin outputs to something that accepts liquids, like another basin.

I also noticed that you can not have the basin output to a chute and a second basin at the same time. I do wonder how it is supposed to handle the hydrogen/oxygen/coppersheet/zincsheet quad output recipe tho in that case...
