### ISSUE TITLE
Eternal Stella can be applied to tinker's tools, does nothing

### ISSUE THREAD

**Issue by DrakulaMan** [simibubi/Above-and-Beyond#93]
When the eternal stella is applied to a tinkers tool, it simply adds the tooltip of 'indestructible', but after one use of this tool that decreases durability, it simply removes this effect, seemingly doing nothing.
![a](https://user-images.githubusercontent.com/39234434/141082934-78fdc09d-16e8-4e3c-8cb7-8d393469a824.png)
![b](https://user-images.githubusercontent.com/39234434/141082947-3d876d9c-e930-4a5b-9731-49070443917a.png)

**Comment by opticGT** [comment]
u can make tinkers tools unbreakable with reinforcement

**Comment by i3ym** [comment]
It works if you don't have luck or silky
at least worked in 1.1
