### ISSUE TITLE
some items from mods appear as question mark in quest gui

### ISSUE THREAD

**Issue by wiktorux1** [simibubi/Above-and-Beyond#94]
when i go to quest gui, some items from mods appear as question mark. i cant craft them, and it is not visible in JEI

**Comment by BD103** [comment]
Did you add/remove any mods? Are you on version 1.1?

**Comment by wiktorux1** [comment]
i added optifine and i'm on version 1.1

**Comment by BD103** [comment]
Optifine messes with many different rendering things, most notably [Tinker's Construct](https://github.com/SlimeKnights/TinkersConstruct/issues/4316). Do you know what specific items are disappearing? Where are they in the quests tab? (Eg. Chapter 1)

Try debugging by removing Optifine and seeing if they still appear incorrectly.

**Comment by wiktorux1** [comment]
i removed optifine and its still the same, and disappearing items are andesite machine and kinetic mechanizm

**Comment by wiktorux1** [comment]
and i can craft flint saw but its not appearing in quests

**Comment by BD103** [comment]
How did you install the modpack? Manually or through a launcher? You may want to try to reinstall the pack. Could you supply screenshots of the errors?

**Comment by wiktorux1** [comment]
i installed it through a launcher

**Comment by wiktorux1** [comment]
![2021-11-23_18 12 25](https://user-images.githubusercontent.com/94048017/143072078-15b5643f-5cc1-4fe9-8ef6-f5a9896e66bc.png)
![2021-11-23_18 12 32](https://user-images.githubusercontent.com/94048017/143072090-67dc0952-862e-4a1a-afa9-4fd7d4f2e603.png)
![2021-11-23_18 12 38](https://user-images.githubusercontent.com/94048017/143072096-f235380e-5dfb-44a0-a3e0-b10d46995edb.png)

**Comment by BD103** [comment]
I have found [the texture](https://github.com/FTBTeam/FTB-Quests/blob/main/common/src/main/resources/assets/ftbquests/textures/item/missing_item.png) for the question mark. It appears that FTB-Quests cannot find the texture for the item. My best recommendations are:

1. Redownload the modpack and reinstall it
2. Go to the [FeedTheBeast Discord](https://ftb.team/discord) and ask for help
3. Go to the [Create mod Discord](https://discord.gg/hmaD7Se) and ask for help

I'm sorry I wasn't able to solve your issue, but I hope these sources help. :D
