### ISSUE TITLE
[Recipe Conflict] Vanilla Chain recipe conflicts with Forbidden & Arcanus Iron Chain recipe

### ISSUE THREAD

**Issue by GE0NE** [simibubi/Above-and-Beyond#95]
The recipe for Forbidden & Arcanus Iron Chain is the same as the recipe for vanilla chains, making it impossible to craft vanilla chains through a crafting table. However, vanilla chains can be created through the Mechanical Crafter, but not the Forbidden & Arcanus Iron Chains
![image](https://user-images.githubusercontent.com/25130343/141153714-1201e3d2-5439-4893-876e-d09ea2a594f5.png)
![image](https://user-images.githubusercontent.com/25130343/141153756-3724f1bf-e26d-400c-bdf1-62e76478f475.png)

**Comment by corintho** [comment]
Fixed on 1.2:
`Fixed a recipe conflict between forbidden arcanus and ..vanilla minecraft`
Now, the recipe will craft a vanilla chain, and you can put the vanilla chain alone in the crafting grid to get 3 F&A chains
