### ISSUE TITLE
Tinkers Construct's 'Necrotic Bones' not dropping

### ISSUE THREAD

**Issue by SwiftKie** [simibubi/Above-and-Beyond#97]
First noticed whilst trying to obtain them in survival,
So I tested in creative with a looting 1000 sword & sure enough non dropped

(Maybe related to the fact that Architects Palette adds it own Wither Bones)

**Comment by AIBuildo** [comment]
I've been getting them with looting 3, but they are a bit rare.

**Comment by SwiftKie** [comment]
> I've been getting them with looting 3, but they are a bit rare.

Do you mean the wither bones?
cos u can't be talking about the necrotic bones as even with looting 1000 in creative i can't get it

**Comment by AIBuildo** [comment]
The necrotic bones used to add severing to tinker's items.  I may have used a cleaver with luckiest on it to get them, I'm not really sure.
