### ISSUE TITLE
[Suggestion] Add bees to the Market

### ISSUE THREAD

**Issue by shBLOCK** [simibubi/Above-and-Beyond#98]
I found it so hard to find bees in this pack. I just want to make a sealed pattern from chisel and bits...
I even tried to find it in a creative world, and I found it 7000 blocks away...
Maybe add a bee nest with bees in it to the Market.

**Comment by GoliathX211** [comment]
Or honey bottles. I think the point of the market is that if you're relying on it you will need to buy from it again
Getting a beehive would be a one time purchase in a way.
